//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در پردازش داده های دریافت شده خطایی رخ داده است.
        /// </summary>
        public static string msg_ErrorOnReciveData {
            get {
                return ResourceManager.GetString("msg_ErrorOnReciveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا اطلاعات را به شکل صحیح وارد نمایید.
        /// </summary>
        public static string pub_EnterDate {
            get {
                return ResourceManager.GetString("pub_EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ثبت اطلاعات با خطا مواجه گردید! لطفا مجددا سعی نمایید.
        /// </summary>
        public static string pub_RegistrationHasError {
            get {
                return ResourceManager.GetString("pub_RegistrationHasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا اطلاعات را به شکل صحیح وارد نمایید.
        /// </summary>
        public static string pub_RequiredField {
            get {
                return ResourceManager.GetString("pub_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات {0} را بشکل صحیح وارد نمایید.
        /// </summary>
        public static string RequiredField_Anot {
            get {
                return ResourceManager.GetString("RequiredField_Anot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string TblAnot_CustomerGrade_CustomerGradeID {
            get {
                return ResourceManager.GetString("TblAnot_CustomerGrade_CustomerGradeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان درجه.
        /// </summary>
        public static string TblAnot_CustomerGrade_CustomerGradeName {
            get {
                return ResourceManager.GetString("TblAnot_CustomerGrade_CustomerGradeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string TblAnot_CustomerGrade_IsActive {
            get {
                return ResourceManager.GetString("TblAnot_CustomerGrade_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string TblAnot_Province_IsActive {
            get {
                return ResourceManager.GetString("TblAnot_Province_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد استان.
        /// </summary>
        public static string TblAnot_Province_ProvinceCode {
            get {
                return ResourceManager.GetString("TblAnot_Province_ProvinceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string TblAnot_Province_ProvinceID {
            get {
                return ResourceManager.GetString("TblAnot_Province_ProvinceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام لاتین استان.
        /// </summary>
        public static string TblAnot_Province_ProvinceLatinName {
            get {
                return ResourceManager.GetString("TblAnot_Province_ProvinceLatinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام استان.
        /// </summary>
        public static string TblAnot_Province_ProvinceName {
            get {
                return ResourceManager.GetString("TblAnot_Province_ProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string TblAnot_RawMaterial_IsActive {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterial_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ماده مصرفی.
        /// </summary>
        public static string TblAnot_RawMaterial_RawMaterialCode {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterial_RawMaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه گروه.
        /// </summary>
        public static string TblAnot_RawMaterial_RawMaterialGroupID {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterial_RawMaterialGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string TblAnot_RawMaterial_RawMaterialID {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterial_RawMaterialID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان لاتین ماده مصرفی.
        /// </summary>
        public static string TblAnot_RawMaterial_RawMaterialLatinName {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterial_RawMaterialLatinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان ماده مصرفی.
        /// </summary>
        public static string TblAnot_RawMaterial_RawMaterialName {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterial_RawMaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اصلی ماده مصرفی.
        /// </summary>
        public static string TblAnot_RawMaterial_RawMaterialOriginCode {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterial_RawMaterialOriginCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان اصلی ماده مصرفی.
        /// </summary>
        public static string TblAnot_RawMaterial_RawMaterialOriginName {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterial_RawMaterialOriginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد.
        /// </summary>
        public static string TblAnot_RawMaterial_UnitID {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterial_UnitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال است.
        /// </summary>
        public static string TblAnot_RawMaterialGroup_IsActive {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterialGroup_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مایع است.
        /// </summary>
        public static string TblAnot_RawMaterialGroup_IsLiquid {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterialGroup_IsLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا بازیافتی است.
        /// </summary>
        public static string TblAnot_RawMaterialGroup_IsRecycled {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterialGroup_IsRecycled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string TblAnot_RawMaterialGroup_RawMaterialGroupID {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterialGroup_RawMaterialGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان لاتین.
        /// </summary>
        public static string TblAnot_RawMaterialGroup_RawMaterialGroupLatinName {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterialGroup_RawMaterialGroupLatinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان گروه مواد.
        /// </summary>
        public static string TblAnot_RawMaterialGroup_RawMaterialGroupName {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterialGroup_RawMaterialGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرایط نگهداری.
        /// </summary>
        public static string TblAnot_RawMaterialGroup_StorageConditions {
            get {
                return ResourceManager.GetString("TblAnot_RawMaterialGroup_StorageConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string TblAnot_SaleAgent_Address {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص مرتبط.
        /// </summary>
        public static string TblAnot_SaleAgent_ContactPerson {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجه مشتری.
        /// </summary>
        public static string TblAnot_SaleAgent_CustomerGradeID {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_CustomerGradeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string TblAnot_SaleAgent_IsActive {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خارجی.
        /// </summary>
        public static string TblAnot_SaleAgent_IsForeign {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_IsForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string TblAnot_SaleAgent_ProvinceID {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_ProvinceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتیاز مشتری.
        /// </summary>
        public static string TblAnot_SaleAgent_Rating {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نمایندگی.
        /// </summary>
        public static string TblAnot_SaleAgent_SaleAgentCode {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_SaleAgentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string TblAnot_SaleAgent_SaleAgentID {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_SaleAgentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام لاتین.
        /// </summary>
        public static string TblAnot_SaleAgent_SaleAgentLatinName {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_SaleAgentLatinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فارسی.
        /// </summary>
        public static string TblAnot_SaleAgent_SaleAgentLocalizedName {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_SaleAgentLocalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نمایندگی.
        /// </summary>
        public static string TblAnot_SaleAgent_SaleAgentName {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_SaleAgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع بکار.
        /// </summary>
        public static string TblAnot_SaleAgent_StartDate {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        public static string TblAnot_SaleAgent_Tel {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی.
        /// </summary>
        public static string TblAnot_SaleAgent_ZipCode {
            get {
                return ResourceManager.GetString("TblAnot_SaleAgent_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalendarCultureInfo.
        /// </summary>
        public static string TblAnot_SettingGeneral_CalendarCultureInfo {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_CalendarCultureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyDecimalSeparator.
        /// </summary>
        public static string TblAnot_SettingGeneral_CurrencyDecimalSeparator {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_CurrencyDecimalSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoryCode.
        /// </summary>
        public static string TblAnot_SettingGeneral_FactoryCode {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_FactoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام لاتین شرکت.
        /// </summary>
        public static string TblAnot_SettingGeneral_FactoryNameEn {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_FactoryNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فارسی شرکت.
        /// </summary>
        public static string TblAnot_SettingGeneral_FactoryNameFa {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_FactoryNameFa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphicAuthorizedTimesGetDossier.
        /// </summary>
        public static string TblAnot_SettingGeneral_GraphicAuthorizedTimesGetDossier {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_GraphicAuthorizedTimesGetDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogButtonsClick.
        /// </summary>
        public static string TblAnot_SettingGeneral_LogButtonsClick {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_LogButtonsClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogClosingForm.
        /// </summary>
        public static string TblAnot_SettingGeneral_LogClosingForm {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_LogClosingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOpeningForm.
        /// </summary>
        public static string TblAnot_SettingGeneral_LogOpeningForm {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_LogOpeningForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxSizeOfJobImage.
        /// </summary>
        public static string TblAnot_SettingGeneral_MaxSizeOfJobImage {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_MaxSizeOfJobImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderRequestToExcelSetting.
        /// </summary>
        public static string TblAnot_SettingGeneral_OrderRequestToExcelSetting {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_OrderRequestToExcelSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportCustomerDraftFormCode.
        /// </summary>
        public static string TblAnot_SettingGeneral_ReportCustomerDraftFormCode {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_ReportCustomerDraftFormCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingGeneralID.
        /// </summary>
        public static string TblAnot_SettingGeneral_SettingGeneralID {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_SettingGeneralID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه.
        /// </summary>
        public static string TblAnot_SettingGeneral_SystemVersion {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_SystemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temp.
        /// </summary>
        public static string TblAnot_SettingGeneral_temp {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات تست پلن وارد نشده است.
        /// </summary>
        public static string TestPlanDetailNotExist {
            get {
                return ResourceManager.GetString("TestPlanDetailNotExist", resourceCulture);
            }
        }
    }
}
