//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPC.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPC.Core.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalendarCultureInfo.
        /// </summary>
        internal static string TblAnot_SettingGeneral_CalendarCultureInfo {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_CalendarCultureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyDecimalSeparator.
        /// </summary>
        internal static string TblAnot_SettingGeneral_CurrencyDecimalSeparator {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_CurrencyDecimalSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactoryCode.
        /// </summary>
        internal static string TblAnot_SettingGeneral_FactoryCode {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_FactoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام لاتین شرکت.
        /// </summary>
        internal static string TblAnot_SettingGeneral_FactoryNameEn {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_FactoryNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فارسی شرکت.
        /// </summary>
        internal static string TblAnot_SettingGeneral_FactoryNameFa {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_FactoryNameFa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphicAuthorizedTimesGetDossier.
        /// </summary>
        internal static string TblAnot_SettingGeneral_GraphicAuthorizedTimesGetDossier {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_GraphicAuthorizedTimesGetDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogButtonsClick.
        /// </summary>
        internal static string TblAnot_SettingGeneral_LogButtonsClick {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_LogButtonsClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogClosingForm.
        /// </summary>
        internal static string TblAnot_SettingGeneral_LogClosingForm {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_LogClosingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOpeningForm.
        /// </summary>
        internal static string TblAnot_SettingGeneral_LogOpeningForm {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_LogOpeningForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxSizeOfJobImage.
        /// </summary>
        internal static string TblAnot_SettingGeneral_MaxSizeOfJobImage {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_MaxSizeOfJobImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderRequestToExcelSetting.
        /// </summary>
        internal static string TblAnot_SettingGeneral_OrderRequestToExcelSetting {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_OrderRequestToExcelSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportCustomerDraftFormCode.
        /// </summary>
        internal static string TblAnot_SettingGeneral_ReportCustomerDraftFormCode {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_ReportCustomerDraftFormCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingGeneralID.
        /// </summary>
        internal static string TblAnot_SettingGeneral_SettingGeneralID {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_SettingGeneralID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه.
        /// </summary>
        internal static string TblAnot_SettingGeneral_SystemVersion {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_SystemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temp.
        /// </summary>
        internal static string TblAnot_SettingGeneral_temp {
            get {
                return ResourceManager.GetString("TblAnot_SettingGeneral_temp", resourceCulture);
            }
        }
    }
}
