using System;
using System.Data;
//using System.Data.SqlClient;
using Microsoft.Data.SqlClient;
using System.Collections;
using System.Linq;

namespace AtlasCellData.ADO
{
    public class StationTypeDL : BaseDataAccessLayerClass
    {
        #region Base properties and methods(generated by  CodeGenerator) 
        #region private variables
        private System.Int32 mStationTypeID;
        private System.String mStationTypeName;
        private System.String mStationTypeLatinName;
        private System.Boolean mIsActive;
        private System.String mInsDate;
        private System.String mInsTime;
        private UserDL mUser_InsUserID;
        private System.String mEditDate;
        private System.String mEditTime;
        private UserDL mUser_EditUserID;
        private System.Byte[] mRowTime;

        Hashtable FieldValues;
        private Transaction mTransaction;
        #endregion private variables
        #region properties
        /// <summary> 
        /// StationTypeID/// </summary>	 
        //property for field StationTypeID#
        public System.Int32 StationTypeID
        {
            get
            {
                return mStationTypeID;
            }
            set
            {
                mStationTypeID = value;
                upwardShouldLoad();
                try { FieldValues["StationTypeID"] = value; } catch { }
            }
        }
        /// <summary> 
        /// StationTypeName/// </summary>	 
        //property for field StationTypeName#
        public System.String StationTypeName
        {
            get
            {
                if (shouldLoad)
                {
                    this.getInfo();
                    shouldLoad = false;
                }
                return mStationTypeName;
            }
            set
            {
                mStationTypeName = value;
                try { FieldValues["StationTypeName"] = value; } catch { }
            }
        }
        /// <summary> 
        /// StationTypeLatinName/// </summary>	 
        //property for field StationTypeLatinName#
        public System.String StationTypeLatinName
        {
            get
            {
                if (shouldLoad)
                {
                    this.getInfo();
                    shouldLoad = false;
                }
                return mStationTypeLatinName;
            }
            set
            {
                mStationTypeLatinName = value;
                try { FieldValues["StationTypeLatinName"] = value; } catch { }
            }
        }
        /// <summary> 
        /// IsActive/// </summary>	 
        //property for field IsActive#
        public System.Boolean IsActive
        {
            get
            {
                if (shouldLoad)
                {
                    this.getInfo();
                    shouldLoad = false;
                }
                return mIsActive;
            }
            set
            {
                mIsActive = value;
                try { FieldValues["IsActive"] = value; } catch { }
            }
        }
        /// <summary> 
        /// InsDate/// </summary>	 
        //property for field InsDate#
        public System.String InsDate
        {
            get
            {
                if (shouldLoad)
                {
                    this.getInfo();
                    shouldLoad = false;
                }
                return mInsDate;
            }
            set
            {
                mInsDate = value;
                try { FieldValues["InsDate"] = value; } catch { }
            }
        }
        /// <summary> 
        /// InsTime/// </summary>	 
        //property for field InsTime#
        public System.String InsTime
        {
            get
            {
                if (shouldLoad)
                {
                    this.getInfo();
                    shouldLoad = false;
                }
                return mInsTime;
            }
            set
            {
                mInsTime = value;
                try { FieldValues["InsTime"] = value; } catch { }
            }
        }
        /// <summary> 
        /// InsUserID/// </summary>	 
        //property for field InsUserID#
        public UserDL User_InsUserID
        {
            get
            {
                if (shouldLoad)
                {
                    this.getInfo();
                    shouldLoad = false;
                }
                return mUser_InsUserID;
            }
            set
            {
                mUser_InsUserID = value;
                if (value != null) value.Parent = this;
                try { FieldValues["InsUserID"] = value.UserID; } catch { }

            }
        }
        /// <summary> 
        /// EditDate/// </summary>	 
        //property for field EditDate#
        public System.String EditDate
        {
            get
            {
                if (shouldLoad)
                {
                    this.getInfo();
                    shouldLoad = false;
                }
                return mEditDate;
            }
            set
            {
                mEditDate = value;
                try { FieldValues["EditDate"] = value; } catch { }
            }
        }
        /// <summary> 
        /// EditTime/// </summary>	 
        //property for field EditTime#
        public System.String EditTime
        {
            get
            {
                if (shouldLoad)
                {
                    this.getInfo();
                    shouldLoad = false;
                }
                return mEditTime;
            }
            set
            {
                mEditTime = value;
                try { FieldValues["EditTime"] = value; } catch { }
            }
        }
        /// <summary> 
        /// EditUserID/// </summary>	 
        //property for field EditUserID#
        public UserDL User_EditUserID
        {
            get
            {
                if (shouldLoad)
                {
                    this.getInfo();
                    shouldLoad = false;
                }
                return mUser_EditUserID;
            }
            set
            {
                mUser_EditUserID = value;
                if (value != null) value.Parent = this;
                try { FieldValues["EditUserID"] = value.UserID; } catch { }

            }
        }
        /// <summary> 
        /// RowTime/// </summary>	 
        //property for field RowTime#
        public System.Byte[] RowTime
        {
            get
            {
                if (shouldLoad)
                {
                    this.getInfo();
                    shouldLoad = false;
                }
                return mRowTime;
            }
            set
            {
                mRowTime = value;
                try { FieldValues["RowTime"] = value; } catch { }
            }
        }
        public Transaction transaction
        {
            get
            {
                return mTransaction;
            }
            set
            {
                if (value != null)
                {
                    sqlConnection = value.sqlTransaction.Connection;
                    sqlCommand.Connection = sqlConnection;
                    sqlCommand.Transaction = value.sqlTransaction;
                }
                mTransaction = value;
            }
        }
        #endregion properties
        #region Private Methods
        internal override void upwardShouldLoad()
        {
            shouldLoad = true;
            if (Parent != null)
                Parent.upwardShouldLoad();
        }

        internal override void upwardShouldLoad(BaseDataAccessLayerClass child)
        {
        }
        #endregion
        #region public methods

        /// <summary>
        ///اطلاعات يک رکورد خاص را برمي گرداند 
        /// </summary>
        public bool getInfo_OldADO()
        {
            OpenConnection();
            DataTable dt = new DataTable(); string strSQL = "";
            strSQL = "select * from [StationType]  where [StationTypeID] ='" + this.StationTypeID.ToString() + "'";
            sqlCommand.CommandText = strSQL;
            sqlCommand.Parameters.Clear();
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                sqlDataAdapter.Fill(dt);
                if (dt.Rows.Count != 1) return false;
                if (dt.Rows[0]["StationTypeID"] != DBNull.Value)
                    StationTypeID = (System.Int32)dt.Rows[0]["StationTypeID"];
                if (dt.Rows[0]["StationTypeName"] != DBNull.Value)
                    StationTypeName = (System.String)dt.Rows[0]["StationTypeName"];
                if (dt.Rows[0]["StationTypeLatinName"] != DBNull.Value)
                    StationTypeLatinName = (System.String)dt.Rows[0]["StationTypeLatinName"];
                if (dt.Rows[0]["IsActive"] != DBNull.Value)
                    IsActive = (System.Boolean)dt.Rows[0]["IsActive"];
                if (dt.Rows[0]["InsDate"] != DBNull.Value)
                    InsDate = (System.String)dt.Rows[0]["InsDate"];
                if (dt.Rows[0]["InsTime"] != DBNull.Value)
                    InsTime = (System.String)dt.Rows[0]["InsTime"];
                if (dt.Rows[0]["InsUserID"] != DBNull.Value)
                {
                    if (this.mUser_InsUserID == null) this.mUser_InsUserID = new UserDL(transaction, this);
                    mUser_InsUserID.UserID = (System.Int32)dt.Rows[0]["InsUserID"];
                }
                else
                    mUser_InsUserID = null;
                if (dt.Rows[0]["EditDate"] != DBNull.Value)
                    EditDate = (System.String)dt.Rows[0]["EditDate"];
                if (dt.Rows[0]["EditTime"] != DBNull.Value)
                    EditTime = (System.String)dt.Rows[0]["EditTime"];
                if (dt.Rows[0]["EditUserID"] != DBNull.Value)
                {
                    if (this.mUser_EditUserID == null) this.mUser_EditUserID = new UserDL(transaction, this);
                    mUser_EditUserID.UserID = (System.Int32)dt.Rows[0]["EditUserID"];
                }
                else
                    mUser_EditUserID = null;
                if (dt.Rows[0]["RowTime"] != DBNull.Value)
                    RowTime = (System.Byte[])dt.Rows[0]["RowTime"];
                shouldLoad = false;
                return true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) CloseConnection();
            }
        }
        /// <summary>
        ///اطلاعات يک رکورد خاص را برمي گرداند 
        /// </summary>
        public bool getInfo()
        {
            OpenConnection();
            DataTable dt = new DataTable(); string strSQL = "";
            strSQL = "select * from [StationType] WHERE StationTypeID=@StationTypeID";
            sqlCommand.Parameters.Clear();
            sqlCommand.Parameters.Add(new  SqlParameter("@StationTypeID", this.StationTypeID));
            sqlCommand.CommandText = strSQL;
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                sqlDataAdapter.Fill(dt);
                if (dt.Rows.Count != 1) return false;
                if (dt.Rows[0]["StationTypeID"] != DBNull.Value)
                    StationTypeID = (System.Int32)dt.Rows[0]["StationTypeID"];
                if (dt.Rows[0]["StationTypeName"] != DBNull.Value)
                    StationTypeName = (System.String)dt.Rows[0]["StationTypeName"];
                if (dt.Rows[0]["StationTypeLatinName"] != DBNull.Value)
                    StationTypeLatinName = (System.String)dt.Rows[0]["StationTypeLatinName"];
                if (dt.Rows[0]["IsActive"] != DBNull.Value)
                    IsActive = (System.Boolean)dt.Rows[0]["IsActive"];
                if (dt.Rows[0]["InsDate"] != DBNull.Value)
                    InsDate = (System.String)dt.Rows[0]["InsDate"];
                if (dt.Rows[0]["InsTime"] != DBNull.Value)
                    InsTime = (System.String)dt.Rows[0]["InsTime"];
                if (dt.Rows[0]["InsUserID"] != DBNull.Value)
                {
                    if (this.mUser_InsUserID == null) this.mUser_InsUserID = new UserDL(transaction, this);
                    mUser_InsUserID.UserID = (System.Int32)dt.Rows[0]["InsUserID"];
                }
                else
                    mUser_InsUserID = null;
                if (dt.Rows[0]["EditDate"] != DBNull.Value)
                    EditDate = (System.String)dt.Rows[0]["EditDate"];
                if (dt.Rows[0]["EditTime"] != DBNull.Value)
                    EditTime = (System.String)dt.Rows[0]["EditTime"];
                if (dt.Rows[0]["EditUserID"] != DBNull.Value)
                {
                    if (this.mUser_EditUserID == null) this.mUser_EditUserID = new UserDL(transaction, this);
                    mUser_EditUserID.UserID = (System.Int32)dt.Rows[0]["EditUserID"];
                }
                else
                    mUser_EditUserID = null;
                if (dt.Rows[0]["RowTime"] != DBNull.Value)
                    RowTime = (System.Byte[])dt.Rows[0]["RowTime"];
                shouldLoad = false;
                return true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) CloseConnection();
            }
        }
        /// <summary>
        ///اطلاعات يک رکورد خاص را برمي گرداند 
        /// </summary>
        public bool getInfo_OLD(params string[] fieldNames)
        {
            string sWhereFields = " where ";
            for (int i = 0; i < fieldNames.Length; i++)
            {
                if (i != fieldNames.Length - 1)
                    if (!(FieldValues[fieldNames[i]].GetType().ToString() == "System.Boolean"))
                        sWhereFields += "[" + fieldNames[i] + "]='" + (FieldValues[fieldNames[i]]).ToString() + "' and ";
                    else
                        sWhereFields += "[" + fieldNames[i] + "]='" + ((bool)FieldValues[fieldNames[i]] ? "1" : "0") + "' and ";
                else
                if (!(FieldValues[fieldNames[i]].GetType().ToString() == "System.Boolean"))
                    sWhereFields += "[" + fieldNames[i] + "]='" + (FieldValues[fieldNames[i]]).ToString() + "'";
                else
                    sWhereFields += "[" + fieldNames[i] + "]='" + ((bool)FieldValues[fieldNames[i]] ? "1" : "0") + "'";
            }
            OpenConnection();
            DataTable dt = new DataTable();
            string strSQL = "";
            strSQL = "select * from [StationType] " + sWhereFields;
            sqlCommand.CommandText = strSQL;
            sqlCommand.Parameters.Clear();
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                sqlDataAdapter.Fill(dt);
                if (dt.Rows.Count != 1) return false;
                if (dt.Rows[0]["StationTypeID"] != DBNull.Value)
                    StationTypeID = (System.Int32)dt.Rows[0]["StationTypeID"];
                if (dt.Rows[0]["StationTypeName"] != DBNull.Value)
                    StationTypeName = (System.String)dt.Rows[0]["StationTypeName"];
                if (dt.Rows[0]["StationTypeLatinName"] != DBNull.Value)
                    StationTypeLatinName = (System.String)dt.Rows[0]["StationTypeLatinName"];
                if (dt.Rows[0]["IsActive"] != DBNull.Value)
                    IsActive = (System.Boolean)dt.Rows[0]["IsActive"];
                if (dt.Rows[0]["InsDate"] != DBNull.Value)
                    InsDate = (System.String)dt.Rows[0]["InsDate"];
                if (dt.Rows[0]["InsTime"] != DBNull.Value)
                    InsTime = (System.String)dt.Rows[0]["InsTime"];
                if (dt.Rows[0]["InsUserID"] != DBNull.Value)
                {
                    if (this.mUser_InsUserID == null) this.mUser_InsUserID = new UserDL(transaction, this);
                    mUser_InsUserID.UserID = (System.Int32)dt.Rows[0]["InsUserID"];
                }
                else
                    mUser_InsUserID = null;
                if (dt.Rows[0]["EditDate"] != DBNull.Value)
                    EditDate = (System.String)dt.Rows[0]["EditDate"];
                if (dt.Rows[0]["EditTime"] != DBNull.Value)
                    EditTime = (System.String)dt.Rows[0]["EditTime"];
                if (dt.Rows[0]["EditUserID"] != DBNull.Value)
                {
                    if (this.mUser_EditUserID == null) this.mUser_EditUserID = new UserDL(transaction, this);
                    mUser_EditUserID.UserID = (System.Int32)dt.Rows[0]["EditUserID"];
                }
                else
                    mUser_EditUserID = null;
                if (dt.Rows[0]["RowTime"] != DBNull.Value)
                    RowTime = (System.Byte[])dt.Rows[0]["RowTime"];
                shouldLoad = false;
                return true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) CloseConnection();
            }
        }
        /// <summary>
        ///اطلاعات يک رکورد خاص را برمي گرداند 
        /// </summary>
        public bool getInfo(params string[] fieldNames)
        {
            string sWhereFields = " where ";
            for (int i = 0; i < fieldNames.Length; i++)
            {
                sWhereFields += "[" + fieldNames[i] + "]=@" + fieldNames[i];
                sWhereFields += (i < fieldNames.Length - 1 ? " and" : "");
            }
            sqlCommand.Parameters.Clear();
            SqlParameter param;
            for (int i = 0; i < fieldNames.Length; i++)
            {
                param = new SqlParameter();
                param.ParameterName = "@" + fieldNames[i];
                param.Value = FieldValues[fieldNames[i]];
                sqlCommand.Parameters.Add(param);
            }
            OpenConnection();
            DataTable dt = new DataTable();
            string strSQL = "";
            strSQL = "select * from [StationType] " + sWhereFields;
            sqlCommand.CommandText = strSQL;
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                sqlDataAdapter.Fill(dt);
                if (dt.Rows.Count != 1) return false;
                if (dt.Rows[0]["StationTypeID"] != DBNull.Value)
                    StationTypeID = (System.Int32)dt.Rows[0]["StationTypeID"];
                if (dt.Rows[0]["StationTypeName"] != DBNull.Value)
                    StationTypeName = (System.String)dt.Rows[0]["StationTypeName"];
                if (dt.Rows[0]["StationTypeLatinName"] != DBNull.Value)
                    StationTypeLatinName = (System.String)dt.Rows[0]["StationTypeLatinName"];
                if (dt.Rows[0]["IsActive"] != DBNull.Value)
                    IsActive = (System.Boolean)dt.Rows[0]["IsActive"];
                if (dt.Rows[0]["InsDate"] != DBNull.Value)
                    InsDate = (System.String)dt.Rows[0]["InsDate"];
                if (dt.Rows[0]["InsTime"] != DBNull.Value)
                    InsTime = (System.String)dt.Rows[0]["InsTime"];
                if (dt.Rows[0]["InsUserID"] != DBNull.Value)
                {
                    if (this.mUser_InsUserID == null) this.mUser_InsUserID = new UserDL(transaction, this);
                    mUser_InsUserID.UserID = (System.Int32)dt.Rows[0]["InsUserID"];
                }
                else
                    mUser_InsUserID = null;
                if (dt.Rows[0]["EditDate"] != DBNull.Value)
                    EditDate = (System.String)dt.Rows[0]["EditDate"];
                if (dt.Rows[0]["EditTime"] != DBNull.Value)
                    EditTime = (System.String)dt.Rows[0]["EditTime"];
                if (dt.Rows[0]["EditUserID"] != DBNull.Value)
                {
                    if (this.mUser_EditUserID == null) this.mUser_EditUserID = new UserDL(transaction, this);
                    mUser_EditUserID.UserID = (System.Int32)dt.Rows[0]["EditUserID"];
                }
                else
                    mUser_EditUserID = null;
                if (dt.Rows[0]["RowTime"] != DBNull.Value)
                    RowTime = (System.Byte[])dt.Rows[0]["RowTime"];
                shouldLoad = false;
                return true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) CloseConnection();
            }
        }

        /// <summary>
        /// يک رکورد خاص را ويرايش مي کند
        /// </summary>
        public bool update_OldADO()
        {
            string strSQL = "";
            strSQL = "update [StationType] set " +
            "[StationTypeID]=" + mStationTypeID.ToString() + "," +
            "[StationTypeName]=N'" + mStationTypeName.ToString() + "'," +
            "[StationTypeLatinName]=N'" + mStationTypeLatinName.ToString() + "'," +
            "[IsActive]=" + (IsActive ? "1" : "0") + "," +
            "[InsDate]=N'" + mInsDate.ToString() + "'," +
            "[InsTime]=N'" + mInsTime.ToString() + "'," +
            "[InsUserID]=" + (mUser_InsUserID != null ? "" + mUser_InsUserID.UserID.ToString() + "" : "null") + "," +
            "[EditDate]=N'" + mEditDate.ToString() + "'," +
            "[EditTime]=N'" + mEditTime.ToString() + "'," +
            "[EditUserID]=" + (mUser_EditUserID != null ? "" + mUser_EditUserID.UserID.ToString() + "" : "null") + ""
            ;
            strSQL += "  where [StationTypeID] ='" + this.StationTypeID.ToString() + "' ";
            sqlCommand.CommandText = strSQL;
            OpenConnection();
            sqlCommand.Parameters.Clear();
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                sqlCommand.ExecuteNonQuery();
                return true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) CloseConnection();
            }
        }
        /// <summary>
        /// يک رکورد خاص را ويرايش مي کند
        /// </summary>
        public bool Update()
        {
            string strSQL = "";
            strSQL = "update [StationType] set StationTypeID=@StationTypeID,StationTypeName=@StationTypeName,StationTypeLatinName=@StationTypeLatinName,IsActive=@IsActive,InsDate=@InsDate,InsTime=@InsTime,InsUserID=@InsUserID,EditDate=@EditDate,EditTime=@EditTime,EditUserID=@EditUserID";
            strSQL += " WHERE StationTypeID=@StationTypeID ";
            sqlCommand.Parameters.Clear();
            sqlCommand.Parameters.Add("@StationTypeID", SqlDbType.Int).Value = mStationTypeID;
            sqlCommand.Parameters.Add("@StationTypeName", SqlDbType.NVarChar).Value = mStationTypeName == null ? (Object)DBNull.Value : mStationTypeName;
            sqlCommand.Parameters.Add("@StationTypeLatinName", SqlDbType.NVarChar).Value = mStationTypeLatinName == null ? (Object)DBNull.Value : mStationTypeLatinName;
            sqlCommand.Parameters.Add("@IsActive", SqlDbType.Bit).Value = mIsActive ? true : false;
            sqlCommand.Parameters.Add("@InsDate", SqlDbType.NVarChar).Value = mInsDate == null ? (Object)DBNull.Value : mInsDate;
            sqlCommand.Parameters.Add("@InsTime", SqlDbType.NVarChar).Value = mInsTime == null ? (Object)DBNull.Value : mInsTime;
            sqlCommand.Parameters.Add(new SqlParameter("@InsUserID", mUser_InsUserID == null ? (Object)DBNull.Value : mUser_InsUserID.UserID));
            sqlCommand.Parameters.Add("@EditDate", SqlDbType.NVarChar).Value = mEditDate == null ? (Object)DBNull.Value : mEditDate;
            sqlCommand.Parameters.Add("@EditTime", SqlDbType.NVarChar).Value = mEditTime == null ? (Object)DBNull.Value : mEditTime;
            sqlCommand.Parameters.Add(new SqlParameter("@EditUserID", mUser_EditUserID == null ? (Object)DBNull.Value : mUser_EditUserID.UserID));
            sqlCommand.CommandText = strSQL;
            OpenConnection();
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                sqlCommand.ExecuteNonQuery();
                return true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) CloseConnection();
            }
        }
        /// <summary>
        /// يک رکورد خاص را ويرايش مي کند
        /// </summary>
        public bool update_OldADO(System.Int32 StationTypeID)
        {
            string strSQL = "";
            strSQL = "update [StationType] set " +
            "[StationTypeID]=" + mStationTypeID.ToString() + "," +
            "[StationTypeName]=N'" + mStationTypeName.ToString() + "'," +
            "[StationTypeLatinName]=N'" + mStationTypeLatinName.ToString() + "'," +
            "[IsActive]=" + (mIsActive ? "1" : "0") + "," +
            "[InsDate]=N'" + mInsDate.ToString() + "'," +
            "[InsTime]=N'" + mInsTime.ToString() + "'," +
            "[InsUserID]=" + (mUser_InsUserID != null ? "" + mUser_InsUserID.UserID.ToString() + "" : "null") + "," +
            "[EditDate]=N'" + mEditDate.ToString() + "'," +
            "[EditTime]=N'" + mEditTime.ToString() + "'," +
            "[EditUserID]=" + (mUser_EditUserID != null ? "" + mUser_EditUserID.UserID.ToString() + "" : "null") + ""
            ;
            strSQL += "   where [StationTypeID] ='" + this.StationTypeID.ToString() + "' ";
            sqlCommand.CommandText = strSQL;
            OpenConnection();
            sqlCommand.Parameters.Clear();
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                sqlCommand.ExecuteNonQuery();
                return true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) CloseConnection();
            }
        }

        /// <summary>
        /// يک رکورد خاص را حذف مي کند 
        /// </summary>
        public bool Delete_OldADO()
        {
            string strSQL = "";
            strSQL = "delete from [StationType]  where [StationTypeID] ='" + this.StationTypeID.ToString() + "'";
            OpenConnection();
            sqlCommand.Parameters.Clear();
            sqlCommand.CommandType = CommandType.Text;
            sqlCommand.CommandText = strSQL;
            try
            {
                sqlCommand.ExecuteNonQuery();
                return true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) CloseConnection();
            }
        }
        /// <summary>
        /// يک رکورد خاص را حذف مي کند 
        /// </summary>
        public bool Delete()
        {
            string strSQL = "";
            strSQL = "delete from [StationType] WHERE StationTypeID=@StationTypeID";
            OpenConnection();
            sqlCommand.Parameters.Clear();
            sqlCommand.Parameters.Add(new SqlParameter("@StationTypeID", this.StationTypeID));
            sqlCommand.CommandType = CommandType.Text;
            sqlCommand.CommandText = strSQL;
            try
            {
                sqlCommand.ExecuteNonQuery();
                return true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) CloseConnection();
            }
        }
        /// <summary>
        /// يک رکورد خاص را حذف مي کند 
        /// </summary>
        public bool delete(params string[] fieldNames)
        {
            if (!this.getInfo(fieldNames)) return false;
            string sWhereFields = "  ";
            for (int i = 0; i < fieldNames.Length; i++)
            {
                if (i != fieldNames.Length - 1)
                    sWhereFields += "[" + fieldNames[i] + "]='" + (FieldValues[fieldNames[i]]).ToString() + "' and ";
                else
                    sWhereFields += "[" + fieldNames[i] + "]='" + (FieldValues[fieldNames[i]]).ToString() + "'";
            }
            string strSQL = "";
            strSQL = "delete from [StationType] where " + sWhereFields;
            OpenConnection();
            sqlCommand.Parameters.Clear();
            sqlCommand.CommandType = CommandType.Text;
            sqlCommand.CommandText = strSQL;
            try
            {
                sqlCommand.ExecuteNonQuery();
                return true;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) CloseConnection();
            }
        }
        
        /// <summary>
        /// يک رکورد را به جدول اضافه مي کند 
        /// </summary>
        public void Append_OldADO()
        {
            string strSQL = "";
            sqlCommand.Parameters.Clear();
            strSQL = @"insert into  [StationType] ([StationTypeID],[StationTypeName],[StationTypeLatinName],[IsActive],[InsDate],[InsTime],[InsUserID],[EditDate],[EditTime],[EditUserID])" +
            "values (" +
            "" + mStationTypeID.ToString() + "," +
            "N'" + mStationTypeName.ToString() + "'" + "," +
            "N'" + mStationTypeLatinName.ToString() + "'" + "," +
            (mIsActive ? "1" : "0") + "," +
            "N'" + mInsDate.ToString() + "'" + "," +
            "N'" + mInsTime.ToString() + "'" + "," +
            (mUser_InsUserID != null ? "'" + mUser_InsUserID.UserID.ToString() + "'" : "null") + "," +
            "N'" + mEditDate.ToString() + "'" + "," +
            "N'" + mEditTime.ToString() + "'" + "," +
            (mUser_EditUserID != null ? "'" + mUser_EditUserID.UserID.ToString() + "'" : "null") +
            ")";
            OpenConnection();
            sqlCommand.CommandText = strSQL;
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                sqlCommand.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) CloseConnection();
            }
        }
        /// <summary>
        /// يک رکورد را به جدول اضافه مي کند 
        /// </summary>
        public void Append()
        {
            string strSQL = "";
            sqlCommand.Parameters.Clear();
            strSQL = @"insert into  [StationType] ([StationTypeID],[StationTypeName],[StationTypeLatinName],[IsActive],[InsDate],[InsTime],[InsUserID],[EditDate],[EditTime],[EditUserID])" +
            "values (@StationTypeID, @StationTypeName, @StationTypeLatinName, @IsActive, @InsDate, @InsTime, @InsUserID, @EditDate, @EditTime, @EditUserID )";
            sqlCommand.Parameters.Clear();
            sqlCommand.Parameters.Add("@StationTypeID", SqlDbType.Int).Value = mStationTypeID;
            sqlCommand.Parameters.Add("@StationTypeName", SqlDbType.NVarChar).Value = mStationTypeName == null ? (Object)DBNull.Value : mStationTypeName;
            sqlCommand.Parameters.Add("@StationTypeLatinName", SqlDbType.NVarChar).Value = mStationTypeLatinName == null ? (Object)DBNull.Value : mStationTypeLatinName;
            sqlCommand.Parameters.Add("@IsActive", SqlDbType.Bit).Value = mIsActive ? true : false;
            sqlCommand.Parameters.Add("@InsDate", SqlDbType.NVarChar).Value = mInsDate == null ? (Object)DBNull.Value : mInsDate;
            sqlCommand.Parameters.Add("@InsTime", SqlDbType.NVarChar).Value = mInsTime == null ? (Object)DBNull.Value : mInsTime;
            sqlCommand.Parameters.Add(new SqlParameter("@InsUserID", mUser_InsUserID == null ? (Object)DBNull.Value : mUser_InsUserID.UserID));
            sqlCommand.Parameters.Add("@EditDate", SqlDbType.NVarChar).Value = mEditDate == null ? (Object)DBNull.Value : mEditDate;
            sqlCommand.Parameters.Add("@EditTime", SqlDbType.NVarChar).Value = mEditTime == null ? (Object)DBNull.Value : mEditTime;
            sqlCommand.Parameters.Add(new SqlParameter("@EditUserID", mUser_EditUserID == null ? (Object)DBNull.Value : mUser_EditUserID.UserID));
            OpenConnection();
            sqlCommand.CommandText = strSQL;
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                sqlCommand.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) CloseConnection();
            }
        }
        public int getOrdinal(string whereExpression, string sortExpression)
        {
            string strSQL = "";
            strSQL = "select [StationTypeID] from [StationType]" +
            (whereExpression == "" ? "" : " where " + whereExpression) +
            (sortExpression == "" ? "" : " order by " + sortExpression);
            OpenConnection();
            sqlCommand.CommandText = strSQL;
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                sqlDataReader = sqlCommand.ExecuteReader();
                int index = 0;
                bool found = false;
                while (sqlDataReader.Read())
                {
                    if ((System.Int32)sqlDataReader["StationTypeID"] == StationTypeID)
                    {
                        found = true;
                        break;
                    }
                    index++;
                }
                sqlDataReader.Close();
                if (transaction == null) CloseConnection();
                if (found) return index; else return -1; ;

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        
        /// <summary>
        /// يكي از توابع تجمعي روي مجموعه اي از ركوردها اعمال ميكند 
        /// </summary>
        public static object aggregate(AggregateType type, string fieldName, string whereExpression)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlCommand sqlCommand = b.sqlCommand;
            SqlTransaction sqlTransaction = b.sqlTransaction;
            SqlConnection sqlConnection = b.sqlConnection;
            SqlDataAdapter sqlDataAdapter = b.sqlDataAdapter;
            SqlDataReader sqlDataReader = b.sqlDataReader;
            string strSQL = "";
            if (whereExpression != "")
                strSQL = string.Format("select {0} ({1}) from [StationType] where {2}",
                                    type.ToString(),
                                    fieldName == "" ? "*" : fieldName,
                                    whereExpression);
            else
                strSQL = string.Format("select {0} ({1}) from [StationType]",
                    type.ToString(),
                    fieldName == "" ? "*" : fieldName);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                object ret = sqlCommand.ExecuteScalar();
                return ret == null || ret == DBNull.Value ? 0 : ret;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                sqlConnection.Close();
            }
        }
        /// <summary>
        /// يكي از توابع تجمعي روي مجموعه اي از ركوردها اعمال ميكند 
        /// </summary>
        public static object aggregate(AggregateType type, string fieldName, string whereExpression, Transaction transaction)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlConnection sqlConnection;
            sqlConnection = transaction.sqlTransaction.Connection;
            SqlCommand sqlCommand = new Microsoft.Data.SqlClient.SqlCommand();
            sqlCommand.Connection = sqlConnection;
            sqlCommand.Transaction = transaction.sqlTransaction;
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
            string strSQL = "";
            if (whereExpression != "")
                strSQL = string.Format("select {0} ({1}) from [StationType] where {2}",
                                    type.ToString(),
                                    fieldName == "" ? "*" : fieldName,
                                    whereExpression);
            else
                strSQL = string.Format("select {0} ({1}) from [StationType]",
                    type.ToString(),
                    fieldName == "" ? "*" : fieldName);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                object ret = sqlCommand.ExecuteScalar();
                return ret == null || ret == DBNull.Value ? 0 : ret;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) sqlConnection.Close();
            }
        }
       
        /// <summary>
        /// تعداد ركوردهاي متناظر با شرايط داده شده را بر مي گرداند 
        /// </summary>
        public static long count(string whereExpression)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlCommand sqlCommand = b.sqlCommand;
            SqlTransaction sqlTransaction = b.sqlTransaction;
            SqlConnection sqlConnection = b.sqlConnection;
            SqlDataAdapter sqlDataAdapter = b.sqlDataAdapter;
            SqlDataReader sqlDataReader = b.sqlDataReader;
            string strSQL = "";
            if (whereExpression != "")
                strSQL = string.Format("select count(*)  from [StationType] where {0}",
                    whereExpression);
            else
                strSQL = string.Format("select count(*)  from [StationType]");
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                object ret = sqlCommand.ExecuteScalar();
                return ret == null || ret == DBNull.Value ? 0 : long.Parse(ret.ToString());
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                sqlConnection.Close();
            }
        }
        /// <summary>
        /// تعداد ركوردهاي متناظر با مقدار فیلد داده شده را بر مي گرداند 
        /// </summary>
        public static long count(string fieldName, string fieldValue)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlCommand sqlCommand = b.sqlCommand;
            SqlTransaction sqlTransaction = b.sqlTransaction;
            SqlConnection sqlConnection = b.sqlConnection;
            SqlDataAdapter sqlDataAdapter = b.sqlDataAdapter;
            SqlDataReader sqlDataReader = b.sqlDataReader;
            string strSQL = "";
            strSQL = string.Format("select count(*)  from [StationType] where {0}=@param", fieldName);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try
                {
                    sqlConnection.Open();
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            sqlCommand.Parameters.Clear();
            sqlCommand.Parameters.Add(new SqlParameter("@param", fieldValue));
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                object ret = sqlCommand.ExecuteScalar();
                return ret == null || ret == DBNull.Value ? 0 : long.Parse(ret.ToString());
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                sqlConnection.Close();
            }
        }
        /// <summary>
        /// تعداد ركوردهاي متناظر با شرايط داده شده را بر مي گرداند 
        /// </summary>
        public static long count(string whereExpression, Transaction transaction)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlConnection sqlConnection;
            sqlConnection = transaction.sqlTransaction.Connection;
            SqlCommand sqlCommand = new Microsoft.Data.SqlClient.SqlCommand();
            sqlCommand.Connection = sqlConnection;
            sqlCommand.Transaction = transaction.sqlTransaction;
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
            string strSQL = "";
            if (whereExpression != "")
                strSQL = string.Format("select count(*)  from [StationType] where {0}",
                    whereExpression);
            else
                strSQL = string.Format("select count(*)  from [StationType]");
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                object ret = sqlCommand.ExecuteScalar();
                return ret == null || ret == DBNull.Value ? 0 : long.Parse(ret.ToString());
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) sqlConnection.Close();
            }
        }
        /// <summary>
        /// تعداد ركوردهاي متناظر با مقدار فیلد داده شده را بر مي گرداند 
        /// </summary>
        public static long count(string fieldName, string fieldValue, Transaction transaction)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlConnection sqlConnection;
            sqlConnection = transaction.sqlTransaction.Connection;
            SqlCommand sqlCommand = new Microsoft.Data.SqlClient.SqlCommand();
            sqlCommand.Connection = sqlConnection;
            sqlCommand.Transaction = transaction.sqlTransaction;
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
            string strSQL = "";
            strSQL = string.Format("select count(*)  from [StationType] where {0}=@param", fieldName);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try
                {
                    sqlConnection.Open();
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            sqlCommand.Parameters.Clear();
            sqlCommand.Parameters.Add(new SqlParameter("@param", fieldValue));
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                object ret = sqlCommand.ExecuteScalar();
                return ret == null || ret == DBNull.Value ? 0 : long.Parse(ret.ToString());
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) sqlConnection.Close();
            }
        }
        /// <summary> 
        /// اين تابع مجموعه اي از ركوردها را ويرايش مي كند و تعداد ركورد ويرايش شده را برمي گرداند
        /// </summary>
        public static long updateRecords(string whereExpression, string setExpression)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlCommand sqlCommand = b.sqlCommand;
            SqlTransaction sqlTransaction = b.sqlTransaction;
            SqlConnection sqlConnection = b.sqlConnection;
            SqlDataAdapter sqlDataAdapter = b.sqlDataAdapter;
            SqlDataReader sqlDataReader = b.sqlDataReader;
            string strSQL = "";
            if (whereExpression != "")
                strSQL = string.Format("update [StationType] set {0}   where {1}",
                    setExpression,
                    whereExpression);
            else
                strSQL = string.Format("update [StationType] set {0}   ",
                    setExpression);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                return sqlCommand.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                sqlConnection.Close();
            }
        }
        /// <summary> 
        /// اين تابع مجموعه اي از ركوردها را ويرايش مي كند و تعداد ركورد ويرايش شده را برمي گرداند
        /// </summary>
        public static long updateRecords(string whereExpression, string setExpression, Transaction transaction)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlConnection sqlConnection;
            sqlConnection = transaction.sqlTransaction.Connection;
            SqlCommand sqlCommand = new Microsoft.Data.SqlClient.SqlCommand();
            sqlCommand.Connection = sqlConnection;
            sqlCommand.Transaction = transaction.sqlTransaction;
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
            string strSQL = "";
            if (whereExpression != "")
                strSQL = string.Format("update [StationType] set {0}   where {1}",
                    setExpression,
                    whereExpression);
            else
                strSQL = string.Format("update [StationType] set {0}   ",
                    setExpression);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                return sqlCommand.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) sqlConnection.Close();
            }
        }
        /// <summary>		
        /// اين تابع مجموعه اي از ركوردها را حذف مي كند و تعداد ركوردهاي حذف شده برگرداننده مي شود
        /// </summary>
        public static long deleteRecords(string whereExpression)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlCommand sqlCommand = b.sqlCommand;
            SqlTransaction sqlTransaction = b.sqlTransaction;
            SqlConnection sqlConnection = b.sqlConnection;
            SqlDataAdapter sqlDataAdapter = b.sqlDataAdapter;
            SqlDataReader sqlDataReader = b.sqlDataReader;
            string strSQL = "";
            if (whereExpression != "")
                strSQL = string.Format("delete from [StationType]   where {0}",
                    whereExpression);
            else
                strSQL = string.Format("delete from [StationType]  ");
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                return sqlCommand.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                sqlConnection.Close();
            }

        }
        /// <summary>		
        /// اين تابع مجموعه اي از ركوردها را حذف مي كند و تعداد ركوردهاي حذف شده برگرداننده مي شود
        /// </summary>
        public static long deleteRecords(string fieldName, string fieldValue)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlCommand sqlCommand = b.sqlCommand;
            SqlTransaction sqlTransaction = b.sqlTransaction;
            SqlConnection sqlConnection = b.sqlConnection;
            SqlDataAdapter sqlDataAdapter = b.sqlDataAdapter;
            SqlDataReader sqlDataReader = b.sqlDataReader;
            string strSQL = "";
            strSQL = string.Format("delete from [StationType]   where {0}=@param", fieldName);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try
                {
                    sqlConnection.Open();
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            sqlCommand.Parameters.Clear();
            sqlCommand.Parameters.Add(new SqlParameter("@param", fieldValue));
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                return sqlCommand.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                sqlConnection.Close();
            }

        }
        /// <summary>		
        /// اين تابع مجموعه اي از ركوردها را حذف مي كند و تعداد ركوردهاي حذف شده برگرداننده مي شود
        /// </summary>
        public static long deleteRecords(string whereExpression, Transaction transaction)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlConnection sqlConnection;
            sqlConnection = transaction.sqlTransaction.Connection;
            SqlCommand sqlCommand = new Microsoft.Data.SqlClient.SqlCommand();
            sqlCommand.Connection = sqlConnection;
            sqlCommand.Transaction = transaction.sqlTransaction;
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
            string strSQL = "";
            if (whereExpression != "")
                strSQL = string.Format("delete from [StationType]   where {0}",
                    whereExpression);
            else
                strSQL = string.Format("delete from [StationType]  ");
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                return sqlCommand.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) sqlConnection.Close();
            }

        }
        /// <summary>		
        /// اين تابع مجموعه اي از ركوردها را حذف مي كند و تعداد ركوردهاي حذف شده برگرداننده مي شود
        /// </summary>
        public static long deleteRecords(string fieldName, string fieldValue, Transaction transaction)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlConnection sqlConnection;
            sqlConnection = transaction.sqlTransaction.Connection;
            SqlCommand sqlCommand = new Microsoft.Data.SqlClient.SqlCommand();
            sqlCommand.Connection = sqlConnection;
            sqlCommand.Transaction = transaction.sqlTransaction;
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
            string strSQL = "";
            strSQL = string.Format("delete from [StationType]   where {0}=@param", fieldName);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try
                {
                    sqlConnection.Open();
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            sqlCommand.Parameters.Clear();
            sqlCommand.Parameters.Add(new SqlParameter("@param", fieldValue));
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                return sqlCommand.ExecuteNonQuery();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) sqlConnection.Close();
            }

        }
        /// <summary> 		
        /// مجموعه اي از ركوردهاي جدول در قالب جدول داده بر مي گرداند
        /// </summary>
        public static DataTable getRecords(string selectExpression, string whereExpression,
            string sortExpression, int startIndex, int maxRecords)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlCommand sqlCommand = b.sqlCommand;
            SqlTransaction sqlTransaction = b.sqlTransaction;
            SqlConnection sqlConnection = b.sqlConnection;
            SqlDataAdapter sqlDataAdapter = b.sqlDataAdapter;
            SqlDataReader sqlDataReader = b.sqlDataReader;
            string strSQL = "";
            strSQL = string.Format("select {0} from [StationType]  {1}  {2}",
                    selectExpression == "" ? "*" : selectExpression,
                whereExpression == "" ? "" : "where " + whereExpression,
                sortExpression == "" ? "" : " order by " + sortExpression);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                DataSet DS = new DataSet();
                sqlDataAdapter.Fill(DS, startIndex, maxRecords, "StationType");
                return DS.Tables[0];

            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                sqlConnection.Close();
            }
        }
        /// <summary> 		
        /// مجموعه اي از ركوردهاي جدول در قالب جدول داده بر مي گرداند
        /// </summary>
        public static DataTable getRecords(string selectExpression, string whereExpression,
            string sortExpression, int startIndex, int maxRecords, Transaction transaction)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlConnection sqlConnection;
            sqlConnection = transaction.sqlTransaction.Connection;
            SqlCommand sqlCommand = new Microsoft.Data.SqlClient.SqlCommand();
            sqlCommand.Connection = sqlConnection;
            sqlCommand.Transaction = transaction.sqlTransaction;
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
            string strSQL = "";
            strSQL = string.Format("select {0} from [StationType]  {1}  {2}",
                    selectExpression == "" ? "*" : selectExpression,
                whereExpression == "" ? "" : "where " + whereExpression,
                sortExpression == "" ? "" : " order by " + sortExpression);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                DataSet DS = new DataSet();
                sqlDataAdapter.Fill(DS, startIndex, maxRecords, "StationType");
                return DS.Tables[0];

            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) sqlConnection.Close();
            }
        }
        /// <summary> 	
        /// مجموعه اي از ركوردهاي جدول در قالب جدول داده بر مي گرداند
        /// </summary>
        public static DataTable getRecords(string selectExpression, string whereExpression,
            string sortExpression)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlCommand sqlCommand = b.sqlCommand;
            SqlTransaction sqlTransaction = b.sqlTransaction;
            SqlConnection sqlConnection = b.sqlConnection;
            SqlDataAdapter sqlDataAdapter = b.sqlDataAdapter;
            SqlDataReader sqlDataReader = b.sqlDataReader;
            string strSQL = "";
            strSQL = string.Format("select {0} from [StationType]  {1}  {2}",
                    selectExpression == "" ? "*" : selectExpression,
                whereExpression == "" ? "" : "where " + whereExpression,
                sortExpression == "" ? "" : " order by " + sortExpression);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                DataSet DS = new DataSet();
                sqlDataAdapter.Fill(DS);
                return DS.Tables[0];

            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                sqlConnection.Close();
            }
        }
        /// <summary> 	
        /// مجموعه اي از ركوردهاي جدول در قالب جدول داده بر مي گرداند
        /// </summary>
        public static DataTable getRecords(string selectExpression, string whereExpression,
            string sortExpression, Transaction transaction)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlConnection sqlConnection;
            sqlConnection = transaction.sqlTransaction.Connection;
            SqlCommand sqlCommand = new Microsoft.Data.SqlClient.SqlCommand();
            sqlCommand.Connection = sqlConnection;
            sqlCommand.Transaction = transaction.sqlTransaction;
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
            string strSQL = "";
            strSQL = string.Format("select {0} from [StationType]  {1}  {2}",
                    selectExpression == "" ? "*" : selectExpression,
                whereExpression == "" ? "" : "where " + whereExpression,
                sortExpression == "" ? "" : " order by " + sortExpression);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                DataSet DS = new DataSet();
                sqlDataAdapter.Fill(DS);
                return DS.Tables[0];

            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) sqlConnection.Close();
            }
        }
        
        /// <summary> 	
        /// مجموعه اي از ركوردهاي جدول در قالب جدول داده بر مي گرداند
        /// </summary>
        public static DataTable getRecordsForGrid(string selectExpression, string whereExpression,
            string sortExpression)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlCommand sqlCommand = b.sqlCommand;
            SqlTransaction sqlTransaction = b.sqlTransaction;
            SqlConnection sqlConnection = b.sqlConnection;
            SqlDataAdapter sqlDataAdapter = b.sqlDataAdapter;
            SqlDataReader sqlDataReader = b.sqlDataReader;
            string strSQL = "";
            strSQL = string.Format("select {0} from [StationType]  {1}  {2}",
                    selectExpression == "" ? "*" : selectExpression,
                whereExpression == "" ? "" : "where " + whereExpression,
                sortExpression == "" ? "" : " order by " + sortExpression);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                DataSet DS = new DataSet();
                sqlDataAdapter.Fill(DS);
                return DS.Tables[0];

            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                sqlConnection.Close();
            }
        }
        /// <summary> 	
        /// مجموعه اي از ركوردهاي جدول در قالب جدول داده بر مي گرداند
        /// </summary>
        public static DataTable getRecordsForGrid_SQL(string selectExpression, string whereExpression,
            string sortExpression, Transaction transaction)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlConnection sqlConnection;
            sqlConnection = transaction.sqlTransaction.Connection;
            SqlCommand sqlCommand = new Microsoft.Data.SqlClient.SqlCommand();
            sqlCommand.Connection = sqlConnection;
            sqlCommand.Transaction = transaction.sqlTransaction;
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
            string strSQL = "";
            strSQL = string.Format("select {0} from [StationType]  {1}  {2}",
                    selectExpression == "" ? "*" : selectExpression,
                whereExpression == "" ? "" : "where " + whereExpression,
                sortExpression == "" ? "" : " order by " + sortExpression);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                DataSet DS = new DataSet();
                sqlDataAdapter.Fill(DS);
                return DS.Tables[0];

            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) sqlConnection.Close();
            }
        }
        /// <summary> 		
        /// مجموعه اي از ركوردهاي جدول در قالب آرايه اي از كلاس داده بر مي گرداند
        /// </summary>
        public static StationTypeDL[] getInstances(string whereExpression, int startIndex, int maxRecords)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlCommand sqlCommand = b.sqlCommand;
            SqlTransaction sqlTransaction = b.sqlTransaction;
            SqlConnection sqlConnection = b.sqlConnection;
            SqlDataAdapter sqlDataAdapter = b.sqlDataAdapter;
            SqlDataReader sqlDataReader = b.sqlDataReader;
            string strSQL = "";
            strSQL = string.Format("select * from [StationType]  {0}  ",
                whereExpression == "" ? "" : "where " + whereExpression);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                DataSet DS = new DataSet();
                sqlDataAdapter.Fill(DS, startIndex, maxRecords, "StationType");
                StationTypeDL[] StationTypeDLs = new StationTypeDL[DS.Tables[0].Rows.Count];
                int i = 0;
                foreach (DataRow row in DS.Tables[0].Rows)
                {
                    StationTypeDLs[i] = new StationTypeDL();
                    if (row["StationTypeID"] != DBNull.Value)
                        StationTypeDLs[i].StationTypeID = (System.Int32)row["StationTypeID"];

                    StationTypeDLs[i].getInfo();
                    i++;
                }
                return StationTypeDLs;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                sqlConnection.Close();
            }
        }
        /// <summary> 		
        /// مجموعه اي از ركوردهاي جدول در قالب آرايه اي از كلاس داده بر مي گرداند
        /// </summary>
        public static StationTypeDL[] getInstances(string whereExpression, int startIndex, int maxRecords, Transaction transaction)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlConnection sqlConnection;
            sqlConnection = transaction.sqlTransaction.Connection;
            SqlCommand sqlCommand = new Microsoft.Data.SqlClient.SqlCommand();
            sqlCommand.Connection = sqlConnection;
            sqlCommand.Transaction = transaction.sqlTransaction;
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
            string strSQL = "";
            strSQL = string.Format("select * from [StationType]  {0}  ",
                whereExpression == "" ? "" : "where " + whereExpression);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                DataSet DS = new DataSet();
                sqlDataAdapter.Fill(DS, startIndex, maxRecords, "StationType");
                StationTypeDL[] StationTypeDLs = new StationTypeDL[DS.Tables[0].Rows.Count];
                int i = 0;
                foreach (DataRow row in DS.Tables[0].Rows)
                {
                    StationTypeDLs[i] = new StationTypeDL(transaction);
                    if (row["StationTypeID"] != DBNull.Value)
                        StationTypeDLs[i].StationTypeID = (System.Int32)row["StationTypeID"];

                    StationTypeDLs[i].getInfo();
                    i++;
                }
                return StationTypeDLs;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) sqlConnection.Close();
            }
        }
        /// <summary> 		
        /// مجموعه اي از ركوردهاي جدول در قالب آرايه اي از كلاس داده بر مي گرداند
        /// </summary>
        public static StationTypeDL[] getInstances(string whereExpression)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlCommand sqlCommand = b.sqlCommand;
            SqlTransaction sqlTransaction = b.sqlTransaction;
            SqlConnection sqlConnection = b.sqlConnection;
            SqlDataAdapter sqlDataAdapter = b.sqlDataAdapter;
            SqlDataReader sqlDataReader = b.sqlDataReader;
            string strSQL = "";
            strSQL = string.Format("select * from [StationType]  {0}  ",
                whereExpression == "" ? "" : "where " + whereExpression);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                DataSet DS = new DataSet();
                sqlDataAdapter.Fill(DS);
                StationTypeDL[] StationTypeDLs = new StationTypeDL[DS.Tables[0].Rows.Count];
                int i = 0;
                foreach (DataRow row in DS.Tables[0].Rows)
                {
                    StationTypeDLs[i] = new StationTypeDL();
                    if (row["StationTypeID"] != DBNull.Value)
                        StationTypeDLs[i].StationTypeID = (System.Int32)row["StationTypeID"];

                    StationTypeDLs[i].getInfo();
                    i++;
                }
                return StationTypeDLs;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                sqlConnection.Close();
            }
        }
        /// <summary> 		
        /// مجموعه اي از ركوردهاي جدول در قالب آرايه اي از كلاس داده بر مي گرداند
        /// </summary>
        public static StationTypeDL[] getInstances(string whereExpression, Transaction transaction)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlConnection sqlConnection;
            sqlConnection = transaction.sqlTransaction.Connection;
            SqlCommand sqlCommand = new Microsoft.Data.SqlClient.SqlCommand();
            sqlCommand.Connection = sqlConnection;
            sqlCommand.Transaction = transaction.sqlTransaction;
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
            string strSQL = "";
            strSQL = string.Format("select * from [StationType]  {0}  ",
                whereExpression == "" ? "" : "where " + whereExpression);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                DataSet DS = new DataSet();
                sqlDataAdapter.Fill(DS);
                StationTypeDL[] StationTypeDLs = new StationTypeDL[DS.Tables[0].Rows.Count];
                int i = 0;
                foreach (DataRow row in DS.Tables[0].Rows)
                {
                    StationTypeDLs[i] = new StationTypeDL(transaction);
                    if (row["StationTypeID"] != DBNull.Value)
                        StationTypeDLs[i].StationTypeID = (System.Int32)row["StationTypeID"];

                    StationTypeDLs[i].getInfo();
                    i++;
                }
                return StationTypeDLs;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) sqlConnection.Close();
            }
        }
        /// <summary> 		
        /// مجموعه اي از ركوردهاي جدول در قالب آرايه اي از كلاس داده بر مي گرداند
        /// </summary>
        public static StationTypeDL[] getInstances(string whereExpression, string sortExpression)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlCommand sqlCommand = b.sqlCommand;
            SqlTransaction sqlTransaction = b.sqlTransaction;
            SqlConnection sqlConnection = b.sqlConnection;
            SqlDataAdapter sqlDataAdapter = b.sqlDataAdapter;
            SqlDataReader sqlDataReader = b.sqlDataReader;
            string strSQL = "";
            strSQL = string.Format("select * from [StationType]  {0} {1} ",
                whereExpression == "" ? "" : "where " + whereExpression,
                sortExpression == "" ? "" : "ORDER BY " + sortExpression);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                DataSet DS = new DataSet();
                sqlDataAdapter.Fill(DS);
                StationTypeDL[] StationTypeDLs = new StationTypeDL[DS.Tables[0].Rows.Count];
                int i = 0;
                foreach (DataRow row in DS.Tables[0].Rows)
                {
                    StationTypeDLs[i] = new StationTypeDL();
                    if (row["StationTypeID"] != DBNull.Value)
                        StationTypeDLs[i].StationTypeID = (System.Int32)row["StationTypeID"];

                    StationTypeDLs[i].getInfo();
                    i++;
                }
                return StationTypeDLs;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                sqlConnection.Close();
            }
        }
        /// <summary> 		
        /// مجموعه اي از ركوردهاي جدول در قالب آرايه اي از كلاس داده بر مي گرداند
        /// </summary>
        public static StationTypeDL[] getInstances(string whereExpression, string sortExpression, Transaction transaction)
        {
            BaseDataAccessLayerClass b = new BaseDataAccessLayerClass();
            SqlConnection sqlConnection;
            sqlConnection = transaction.sqlTransaction.Connection;
            SqlCommand sqlCommand = new Microsoft.Data.SqlClient.SqlCommand();
            sqlCommand.Connection = sqlConnection;
            sqlCommand.Transaction = transaction.sqlTransaction;
            SqlDataAdapter sqlDataAdapter = new SqlDataAdapter(sqlCommand);
            string strSQL = "";
            strSQL = string.Format("select * from [StationType]  {0} {1} ",
                whereExpression == "" ? "" : "where " + whereExpression,
                sortExpression == "" ? "" : "ORDER BY " + sortExpression);
            sqlCommand.CommandText = strSQL;
            if (sqlConnection.State == ConnectionState.Closed)
                try { sqlConnection.Open(); } catch (Exception ex) { throw ex; }
            sqlCommand.CommandType = CommandType.Text;
            try
            {
                DataSet DS = new DataSet();
                sqlDataAdapter.Fill(DS);
                StationTypeDL[] StationTypeDLs = new StationTypeDL[DS.Tables[0].Rows.Count];
                int i = 0;
                foreach (DataRow row in DS.Tables[0].Rows)
                {
                    StationTypeDLs[i] = new StationTypeDL(transaction);
                    if (row["StationTypeID"] != DBNull.Value)
                        StationTypeDLs[i].StationTypeID = (System.Int32)row["StationTypeID"];

                    StationTypeDLs[i].getInfo();
                    i++;
                }
                return StationTypeDLs;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                if (transaction == null) sqlConnection.Close();
            }
        }

        #endregion public methods 
        #region Constructors
        public StationTypeDL()
        {

            FieldValues = new Hashtable();
            FieldValues.Add("StationTypeID", null);
            FieldValues.Add("StationTypeName", null);
            FieldValues.Add("StationTypeLatinName", null);
            FieldValues.Add("IsActive", null);
            FieldValues.Add("InsDate", null);
            FieldValues.Add("InsTime", null);
            FieldValues.Add("InsUserID", null);
            FieldValues.Add("EditDate", null);
            FieldValues.Add("EditTime", null);
            FieldValues.Add("EditUserID", null);

        }
        public StationTypeDL(System.Int32 StationTypeID)
        {

            FieldValues = new Hashtable();
            FieldValues.Add("StationTypeID", null);
            FieldValues.Add("StationTypeName", null);
            FieldValues.Add("StationTypeLatinName", null);
            FieldValues.Add("IsActive", null);
            FieldValues.Add("InsDate", null);
            FieldValues.Add("InsTime", null);
            FieldValues.Add("InsUserID", null);
            FieldValues.Add("EditDate", null);
            FieldValues.Add("EditTime", null);
            FieldValues.Add("EditUserID", null);
            this.StationTypeID = StationTypeID;

        }
        public StationTypeDL(Transaction transaction)
        {

            FieldValues = new Hashtable();
            FieldValues.Add("StationTypeID", null);
            FieldValues.Add("StationTypeName", null);
            FieldValues.Add("StationTypeLatinName", null);
            FieldValues.Add("IsActive", null);
            FieldValues.Add("InsDate", null);
            FieldValues.Add("InsTime", null);
            FieldValues.Add("InsUserID", null);
            FieldValues.Add("EditDate", null);
            FieldValues.Add("EditTime", null);
            FieldValues.Add("EditUserID", null);

            this.transaction = transaction;

        }
        public StationTypeDL(System.Int32 StationTypeID, Transaction transaction)
        {

            FieldValues = new Hashtable();
            FieldValues.Add("StationTypeID", null);
            FieldValues.Add("StationTypeName", null);
            FieldValues.Add("StationTypeLatinName", null);
            FieldValues.Add("IsActive", null);
            FieldValues.Add("InsDate", null);
            FieldValues.Add("InsTime", null);
            FieldValues.Add("InsUserID", null);
            FieldValues.Add("EditDate", null);
            FieldValues.Add("EditTime", null);
            FieldValues.Add("EditUserID", null);
            this.StationTypeID = StationTypeID;

            this.transaction = transaction;

        }
        internal StationTypeDL(BaseDataAccessLayerClass parent)
        {
            Parent = parent;

            FieldValues = new Hashtable();
            FieldValues.Add("StationTypeID", null);
            FieldValues.Add("StationTypeName", null);
            FieldValues.Add("StationTypeLatinName", null);
            FieldValues.Add("IsActive", null);
            FieldValues.Add("InsDate", null);
            FieldValues.Add("InsTime", null);
            FieldValues.Add("InsUserID", null);
            FieldValues.Add("EditDate", null);
            FieldValues.Add("EditTime", null);
            FieldValues.Add("EditUserID", null);

        }
        internal StationTypeDL(System.Int32 StationTypeID, BaseDataAccessLayerClass parent)
        {
            Parent = parent;

            FieldValues = new Hashtable();
            FieldValues.Add("StationTypeID", null);
            FieldValues.Add("StationTypeName", null);
            FieldValues.Add("StationTypeLatinName", null);
            FieldValues.Add("IsActive", null);
            FieldValues.Add("InsDate", null);
            FieldValues.Add("InsTime", null);
            FieldValues.Add("InsUserID", null);
            FieldValues.Add("EditDate", null);
            FieldValues.Add("EditTime", null);
            FieldValues.Add("EditUserID", null);
            this.StationTypeID = StationTypeID;

        }
        internal StationTypeDL(Transaction transaction, BaseDataAccessLayerClass parent)
        {
            Parent = parent;

            FieldValues = new Hashtable();
            FieldValues.Add("StationTypeID", null);
            FieldValues.Add("StationTypeName", null);
            FieldValues.Add("StationTypeLatinName", null);
            FieldValues.Add("IsActive", null);
            FieldValues.Add("InsDate", null);
            FieldValues.Add("InsTime", null);
            FieldValues.Add("InsUserID", null);
            FieldValues.Add("EditDate", null);
            FieldValues.Add("EditTime", null);
            FieldValues.Add("EditUserID", null);

            this.transaction = transaction;

        }
        internal StationTypeDL(System.Int32 StationTypeID, Transaction transaction, BaseDataAccessLayerClass parent)
        {
            Parent = parent;

            FieldValues = new Hashtable();
            FieldValues.Add("StationTypeID", null);
            FieldValues.Add("StationTypeName", null);
            FieldValues.Add("StationTypeLatinName", null);
            FieldValues.Add("IsActive", null);
            FieldValues.Add("InsDate", null);
            FieldValues.Add("InsTime", null);
            FieldValues.Add("InsUserID", null);
            FieldValues.Add("EditDate", null);
            FieldValues.Add("EditTime", null);
            FieldValues.Add("EditUserID", null);
            this.StationTypeID = StationTypeID;

            this.transaction = transaction;

        }

        #endregion Constructors
        #endregion Base properties and methods(generated by  CodeGenerator)




    }
}










