using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("AutoCompleteField")]
    public class AutoCompleteField : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("AutoCompleteFieldID")]
        [JsonProperty("AutoCompleteFieldID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int AutoCompleteFieldID { get; set; }

        [Column("FieldName")]
        [JsonProperty("FieldName")]



        public string FieldName { get; set; }

        [Column("FieldValue")]
        [JsonProperty("FieldValue")]



        public string FieldValue { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)
    }
}