using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;

namespace PPC.Core.Models
{
    [Table("BOM")]
    public class BOM : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("BOMID")]
        [JsonProperty("BOMID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int BOMID { get; set; }

        [Column("BOMCode")]
        [JsonProperty("BOMCode")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public string BOMCode { get; set; }

        [Column("ProductID")]
        [JsonProperty("ProductID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int ProductID { get; set; }

        [Column("Status")]
        [JsonProperty("Status")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public byte Status { get; set; }

        [Column("Version")]
        [JsonProperty("Version")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public short Version { get; set; }

        [Column("ParentID")]
        [JsonProperty("ParentID")]
        public int? ParentID { get; set; }

        [Column("IsMainBOM")]
        [JsonProperty("IsMainBOM")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool IsMainBOM { get; set; }

        [Column("Describe")]
        [JsonProperty("Describe")]
        [MaxLength(250)]
        public string Describe { get; set; }


        [Column("Ver")]
        [JsonProperty("Ver")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public short Ver { get; set; }

        [Column("CustomerVer")]
        [JsonProperty("CustomerVer")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public short CustomerVer { get; set; }

        [Column("InsUserID")]
        [JsonProperty("InsUserID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int InsUserID { get; set; }

        [Column("InsUserName")]
        [JsonProperty("InsUserName")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]
        public string InsUserName { get; set; }

        [Column("InsUserFullName")]
        [JsonProperty("InsUserFullName")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string InsUserFullName { get; set; }

        [Column("InsDate")]
        [JsonProperty("InsDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string InsDate { get; set; }

        [Column("InsTime")]
        [JsonProperty("InsTime")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]

        public string InsTime { get; set; }

        [Column("IsDraft")]
        [JsonProperty("IsDraft")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsDraft { get; set; }

        [Column("EditUserID")]
        [JsonProperty("EditUserID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int EditUserID { get; set; }

        [Column("EditUserName")]
        [JsonProperty("EditUserName")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string EditUserName { get; set; }

        [Column("EditUserFullName")]
        [JsonProperty("EditUserFullName")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string EditUserFullName { get; set; }

        [Column("EditDate")]
        [JsonProperty("EditDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string EditDate { get; set; }

        [Column("EditTime")]
        [JsonProperty("EditTime")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]

        public string EditTime { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("Product")]
        [ForeignKey(nameof(ProductID))]
        public Products Product { get; set; }

        [JsonProperty("Parent")]
        [ForeignKey(nameof(ParentID))]
        public BOM Parent { get; set; }

        [JsonProperty("User_InsUser")]
        [ForeignKey(nameof(InsUserID))]
        public Users User_InsUser { get; set; }

        [JsonProperty("User_EditUser")]
        [ForeignKey(nameof(EditUserID))]
        public Users User_EditUser { get; set; }

        [JsonProperty("CustomerDossierList")]
        public List<CustomerDossier> CustomerDossierList { get; set; }

        [JsonProperty("CustomerDossierBOMList")]
        public List<CustomerDossierBOMs> CustomerDossierBOMList { get; set; }

        //[NotMapped]
        //[JsonProperty("CustomerDossier")]
        //public CustomerDossier CustomerDossier { get => CustomerDossierList?.FirstOrDefault(); }


        //[NotMapped]
        [JsonProperty("BOMDetailList")]
        public List<BOMDetail> BOMDetailList { get; set; }

    }
}