using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("BOMComplementary")]
    public class BOMComplementary : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("BOMComplementaryID")]
        [JsonProperty("BOMComplementaryID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int BOMComplementaryID { get; set; }

        [Column("BOMDetailID")]
        [JsonProperty("BOMDetailID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int BOMDetailID { get; set; }

        [Column("RawMaterialID")]
        [JsonProperty("RawMaterialID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int RawMaterialID { get; set; }

        [Column("Priority")]
        [JsonProperty("Priority")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [Range(1, 999.99)] 
        public decimal Priority { get; set; }


        [Column("Percentage")]
        [JsonProperty("Percentage")]
        [Range(0.001, 100)]
        public decimal Percentage { get; set; }

        [Column("Describe")]
        [JsonProperty("Describe")]
        [MaxLength(200)]
        public string Describe { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)


        [JsonProperty("BOMDetail")]
        [ForeignKey(nameof(BOMDetailID))]
        public BOMDetail BOMDetail { get; set; }

        [JsonProperty("RawMaterial")]
        [ForeignKey(nameof(RawMaterialID))]
        public RawMaterials RawMaterial { get; set; }



    }
}