using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PPC.Core.Models
{
    [Table("BOMDetail")]
    public class BOMDetail : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("BOMDetailID")]
        [JsonProperty("BOMDetailID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int BOMDetailID { get; set; }

        [Column("BOMID")]
        [JsonProperty("BOMID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int BOMID { get; set; }

        [Column("RawMaterialID")]
        [JsonProperty("RawMaterialID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int RawMaterialID { get; set; }

        [Column("RMWhiteListID")]
        [JsonProperty("RMWhiteListID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int RMWhiteListID { get; set; }

        [Column("Priority")]
        [JsonProperty("Priority")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public string Priority { get; set; }

        [Column("Percentage")]
        [JsonProperty("Percentage")]
        public decimal? Percentage { get; set; }

        [Column("IsFinalRM")]
        [JsonProperty("IsFinalRM")]
        public bool IsFinalRM { get; set; }

        [Column("Describe")]
        [JsonProperty("Describe")]
        [MaxLength(200)]
        public string Describe { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)



        [JsonProperty("BOM")]
        [ForeignKey(nameof(BOMID))]
        public BOM BOM { get; set; }

        [JsonProperty("RawMaterial")]
        [ForeignKey(nameof(RawMaterialID))]
        public RawMaterials RawMaterial { get; set; }

        [JsonProperty("RMWhiteList")]
        [ForeignKey(nameof(RMWhiteListID))]
        public RMWhiteLists RMWhiteList { get; set; }



        //[NotMapped]
        [JsonProperty("BOMComplementaryList")]
        public List<BOMComplementary> BOMComplementaryList { get; set; }


    }
}