using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using WebApi.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace WebApi.Core.Models
{
    [Table("Country")]
    public class Countries : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("CountryID")]
        [JsonProperty("CountryID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

        public short CountryID { get; set; }

        [Column("CountryName")]
        [JsonProperty("CountryName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public string CountryName { get; set; }

        [Column("CountryLatinName")]
        [JsonProperty("CountryLatinName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public string CountryLatinName { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)
    }
}