using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("Customer")]
    public class Customers : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("CustomerID")]
        [JsonProperty("CustomerID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int CustomerID { get; set; }

        [Column("CustomerCode")]
        [JsonProperty("CustomerCode")]



        public string CustomerCode { get; set; }

        [Column("CustomerName")]
        [JsonProperty("CustomerName")]



        public string CustomerName { get; set; }

        [Column("CustomerLatinName")]
        [JsonProperty("CustomerLatinName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(100)]

        public string CustomerLatinName { get; set; }

        [Column("CustomerLableName")]
        [JsonProperty("CustomerLableName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(100)]

        public string CustomerLableName { get; set; }

        [Column("ProvinceID")]
        [JsonProperty("ProvinceID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public short ProvinceID { get; set; }

        [Column("Address")]
        [JsonProperty("Address")]

        [MaxLength(300)]

        public string Address { get; set; }

        [Column("Tel")]
        [JsonProperty("Tel")]

        [MaxLength(100)]

        public string Tel { get; set; }

        [Column("IsForeign")]
        [JsonProperty("IsForeign")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsForeign { get; set; }

        [Column("ContactPerson")]
        [JsonProperty("ContactPerson")]

        [MaxLength(50)]

        public string ContactPerson { get; set; }

        [Column("InvoicingAddress")]
        [JsonProperty("InvoicingAddress")]

        [MaxLength(500)]

        public string InvoicingAddress { get; set; }

        [Column("DeliveryAddress")]
        [JsonProperty("DeliveryAddress")]

        [MaxLength(500)]

        public string DeliveryAddress { get; set; }

        [Column("IsConfirmed")]
        [JsonProperty("IsConfirmed")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsConfirmed { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsActive { get; set; }

        [Column("Rating")]
        [JsonProperty("Rating")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public decimal Rating { get; set; }

        [Column("StartDate")]
        [JsonProperty("StartDate")]

        [MaxLength(10)]

        public string StartDate { get; set; }

        [Column("CustomerGradeID")]
        [JsonProperty("CustomerGradeID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public short CustomerGradeID { get; set; }

        [Column("ZipCode")]
        [JsonProperty("ZipCode")]

        [MaxLength(15)]

        public string ZipCode { get; set; }

        [Column("NationalIdentity")]
        [JsonProperty("NationalIdentity")]

        [MaxLength(20)]

        public string NationalIdentity { get; set; }

        [Column("RegistrationNumber")]
        [JsonProperty("RegistrationNumber")]

        [MaxLength(20)]

        public string RegistrationNumber { get; set; }

        [Column("EconomicCode")]
        [JsonProperty("EconomicCode")]

        [MaxLength(20)]
       //[Display(Name = "TblAnot_Customer_EconomicCode", ResourceType = typeof(Resources.Resources))]
        public string EconomicCode { get; set; }

        [Column("CEO")]
        [JsonProperty("CEO")]

        [MaxLength(30)]

        public string CEO { get; set; }

        [Column("InvoiceRecipient")]
        [JsonProperty("InvoiceRecipient")]

        [MaxLength(50)]

        public string InvoiceRecipient { get; set; }

        [Column("InsUserID")]
        [JsonProperty("InsUserID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int InsUserID { get; set; }

        [Column("InsDate")]
        [JsonProperty("InsDate")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string InsDate { get; set; }

        [Column("InsTime")]
        [JsonProperty("InsTime")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]

        public string InsTime { get; set; }

        [Column("EditUserID")]
        [JsonProperty("EditUserID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int EditUserID { get; set; }

        [Column("EditDate")]
        [JsonProperty("EditDate")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string EditDate { get; set; }

        [Column("EditTime")]
        [JsonProperty("EditTime")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]

        public string EditTime { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)


        #region Foreign Keys


        [ForeignKey(nameof(ProvinceID))]
        public Provinces Province { get; set; }

        [ForeignKey(nameof(CustomerGradeID))]
        public CustomerGrades CustomerGrade { get; set; }


        [JsonProperty("User_InsUser")]
        [ForeignKey(nameof(InsUserID))]
        public Users User_InsUser { get; set; }

        [JsonProperty("User_EditUser")]
        [ForeignKey(nameof(EditUserID))]
        public Users User_EditUser { get; set; }



        #endregion


        #region Children

        #region Reverts


        /// <summary>
        /// List<Customers>
        /// </summary>
        [ForeignKey(nameof(CustomerID))]
        public virtual List<Reverts> RevertssList { get; set; }

        #endregion



        #endregion




    }
}
