using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("CustomerGrade")]
    public class CustomerGrades : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("CustomerGradeID")]
        [JsonProperty("CustomerGradeID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

        public System.Int16 CustomerGradeID { get; set; }

        [Column("CustomerGradeName")]
        [JsonProperty("CustomerGradeName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(20)]
       //[Display(Name = "TblAnot_CustomerGrade_CustomerGradeName", ResourceType = typeof(Resources.Resources))]
        public string CustomerGradeName { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

       //[Display(Name = "TblAnot_CustomerGrade_IsActive", ResourceType = typeof(Resources.Resources))]
        public bool IsActive { get; set; } = true;

        #endregion Base properties and methods(generated by  CodeGenerator)

        public CustomerGrades()
        {

        }
    }
}
