using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("DensityOfProduct")]
    public class DensityOfProducts : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("DensityID")]
        [JsonProperty("DensityID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int DensityID { get; set; }

        [Column("ProductID")]
        [JsonProperty("ProductID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int ProductID { get; set; }

        [Column("Density")]
        [JsonProperty("Density")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public decimal Density { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("Product")]
        [ForeignKey(nameof(ProductID))]
        public Products Product { get; set; }


    }
}