using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("Instruction")]
    public class Instructions : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("InstructionID")]
        [JsonProperty("InstructionID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

        public short InstructionID { get; set; }

        [Column("InstructionCode")]
        [JsonProperty("InstructionCode")]



        public string InstructionCode { get; set; }

        [Column("InstructionName")]
        [JsonProperty("InstructionName")]



        public string InstructionName { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]



        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)
    }
}