using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;
using System.Collections.Generic;
using PPC.Common;

namespace PPC.Core.Models
{
    [Table("InvRawMaterial")]
    public class InvRawMaterials : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("InvRawMaterialID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int InvRawMaterialID { get; set; }

        [Column("RawMaterialID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int RawMaterialID { get; set; }


        [Column("FinancialRequestNo")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public string FinancialRequestNo { get; set; }

        [Column("InvProductID")]
        public int? InvProductID { get; set; }


        [Column("EntryDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]
        public string EntryDate { get; set; }


        [Column("SupplierID")]
        public short? SupplierID { get; set; }

        [Column("Describe")]
        [MaxLength(250)]
        public string Describe { get; set; }

        [Column("IsSample")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool IsSample { get; set; }

        [Column("Status")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public InvRawMaterialStatus Status { get; set; }


        [Column("InsUserID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int InsUserID { get; set; }


        [Column("InsDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]
        public string InsDate { get; set; }


        [Column("InsTime")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]
        public string InsTime { get; set; }


        [Column("EditUserID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int EditUserID { get; set; }


        [Column("EditDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]
        public string EditDate { get; set; }


        [Column("EditTime")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]
        public string EditTime { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)




        [ForeignKey(nameof(RawMaterialID))]
        public RawMaterials RawMaterial { get; set; }


        [ForeignKey(nameof(SupplierID))]
        public Suppliers Supplier { get; set; }

        [ForeignKey(nameof(InvProductID))]
        public InvProducts InvProduct { get; set; }

        [ForeignKey(nameof(InsUserID))]
        public Users User_InsUser { get; set; }

        [ForeignKey(nameof(EditUserID))]
        public Users User_EditUser { get; set; }



        #region Foreign Keys


        #endregion


        #region Children

        #region InvRawMaterialLots


        /// <summary>
        /// List<InvRawMaterials>
        /// </summary>
        [ForeignKey(nameof(InvRawMaterialID))]
        public virtual List<InvRawMaterialLots> InvRawMaterialLotsList { get; set; }

        #endregion

        #endregion

    }
}