using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;

namespace PPC.Core.Models
{
    [Table("InvRawMaterialLots")]
    public class InvRawMaterialLots : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)

        [Key]
        [Column("InvRawMaterialLotID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int InvRawMaterialLotID { get; set; }


        [Column("LotNo")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public string LotNo { get; set; }


        [Column("IsGenerated")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool IsGenerated { get; set; }


        [Column("ProducedDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]
        public string ProducedDate { get; set; }


        [Column("EnProducedDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]
        public string EnProducedDate { get; set; }


        [Column("ExpireDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]
        public string ExpireDate { get; set; }


        [Column("EnExpireDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]
        public string EnExpireDate { get; set; }


        [Column("ShelfLife")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]
        public string ShelfLife { get; set; }


        [Column("EnShelfLife")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]
        public string EnShelfLife { get; set; }


        [Column("SolidPercentage")]
        [Precision(8, 4)]
        public decimal SolidPercentage { get; set; }


        [Column("QcStatus")]
        public byte QcStatus { get; set; }


        [Column("RNDStatus")]
        public byte RNDStatus { get; set; }


        [Column("Weight")]
        public decimal Weight { get; set; }


        [Column("NetWeight")]
        public decimal NetWeight { get; set; }


        [Column("Describe")]
        public string Describe { get; set; }


        [Column("PalletQty")]
        public short PalletQty { get; set; }





        #endregion Base properties and methods(generated by  CodeGenerator)


        #region Foreign Keys

        #region RawMaterial


        public int RawMaterialID { get; set; }

        /// <summary>
        /// RawMaterial is parent of this
        /// </summary>
        public virtual RawMaterials RawMaterial { get; set; }


        #endregion


        #region PackagingType

        public int PackagingTypeID { get; set; }

        /// <summary>
        /// PackagingType is parent of this
        /// </summary>
        [ForeignKey(nameof(PackagingTypeID))]
        public virtual PackagingTypes PackagingType { get; set; }


        #endregion


        #region InvRawMaterials


        [Column("InvRawMaterialID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int InvRawMaterialID { get; set; }

        public InvRawMaterials InvRawMaterial { get; set; }

        #endregion


        #endregion




        #region Children

        #endregion

    }
}