using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using WebApi.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace WebApi.Core.Models
{
    [Table("MenuAccessState")]
    public class MenuAccessStates : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("MenuAccessStateID")]
        [JsonProperty("MenuAccessStateID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int MenuAccessStateID { get; set; }

        [Column("MenuName")]
        [JsonProperty("MenuName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public string MenuName { get; set; }

        [Column("MenuText")]
        [JsonProperty("MenuText")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public string MenuText { get; set; }

        [Column("State")]
        [JsonProperty("State")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public decimal State { get; set; }

        [Column("MenuGroupID")]
        [JsonProperty("MenuGroupID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public byte MenuGroupID { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)
    }
}