using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("Orders")]
    public class Orders : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("OrderID")]
        [JsonProperty("OrderID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int OrderID { get; set; }

        [Column("OrderNo")]
        [JsonProperty("OrderNo")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public string OrderNo { get; set; }

        [Column("CustomerID")]
        [JsonProperty("CustomerID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int CustomerID { get; set; }

        [Column("SubCustomerID")]
        [JsonProperty("SubCustomerID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int SubCustomerID { get; set; }

        [Column("ConfirmDate")]
        [JsonProperty("ConfirmDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string ConfirmDate { get; set; }

        [Column("CustomerByeNomber")]
        [JsonProperty("CustomerByeNomber")]

        [MaxLength(50)]

        public string CustomerByeNomber { get; set; }

        [Column("Remark")]
        [JsonProperty("Remark")]

        [MaxLength(300)]

        public string Remark { get; set; }

        [Column("Tolerance")]
        [JsonProperty("Tolerance")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public byte Tolerance { get; set; }

        [Column("DeliverFromDate")]
        [JsonProperty("DeliverFromDate")]

        [MaxLength(10)]

        public string DeliverFromDate { get; set; }

        [Column("DeliverToDate")]
        [JsonProperty("DeliverToDate")]

        [MaxLength(10)]

        public string DeliverToDate { get; set; }

        [Column("DeliveredDate")]
        [JsonProperty("DeliveredDate")]

        [MaxLength(10)]

        public string DeliveredDate { get; set; }

        [Column("RegisterDate")]
        [JsonProperty("RegisterDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string RegisterDate { get; set; }

        [Column("Status")]
        [JsonProperty("Status")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public byte Status { get; set; }

        [Column("IsSample")]
        [JsonProperty("IsSample")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsSample { get; set; }

        [Column("DeliverySample")]
        [JsonProperty("DeliverySample")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool DeliverySample { get; set; }

        [Column("DeliveryTestReport")]
        [JsonProperty("DeliveryTestReport")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool DeliveryTestReport { get; set; }

        [Column("PestControlCertificate")]
        [JsonProperty("PestControlCertificate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool PestControlCertificate { get; set; }

        [Column("IsPlanningOrder")]
        [JsonProperty("IsPlanningOrder")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool IsPlanningOrder { get; set; }

        [Column("PaymentMethod")]
        [JsonProperty("PaymentMethod")]

        [MaxLength(50)]

        public string PaymentMethod { get; set; }

        [Column("SendingReason")]
        [JsonProperty("SendingReason")]

        [MaxLength(150)]

        public string SendingReason { get; set; }

        [Column("CustomerIndustry")]
        [JsonProperty("CustomerIndustry")]

        [MaxLength(50)]

        public string CustomerIndustry { get; set; }

        [Column("UserID")]
        [JsonProperty("UserID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int UserID { get; set; }

        [Column("OrderType")]
        [JsonProperty("OrderType")]
        public byte? OrderType { get; set; }

        [Column("InsUserID")]
        [JsonProperty("InsUserID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int InsUserID { get; set; }

        [Column("InsUserName")]
        [JsonProperty("InsUserName")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string InsUserName { get; set; }

        [Column("InsUserFullName")]
        [JsonProperty("InsUserFullName")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string InsUserFullName { get; set; }

        [Column("InsDate")]
        [JsonProperty("InsDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string InsDate { get; set; }

        [Column("InsTime")]
        [JsonProperty("InsTime")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]

        public string InsTime { get; set; }

        [Column("EditUserID")]
        [JsonProperty("EditUserID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int EditUserID { get; set; }

        [Column("EditUserName")]
        [JsonProperty("EditUserName")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]
        public string EditUserName { get; set; }

        [Column("EditUserFullName")]
        [JsonProperty("EditUserFullName")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]
        public string EditUserFullName { get; set; }

        [Column("EditDate")]
        [JsonProperty("EditDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]
        public string EditDate { get; set; }

        [Column("EditTime")]
        [JsonProperty("EditTime")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]

        public string EditTime { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("Customer")]
        [ForeignKey(nameof(CustomerID))]
        public Customers Customer { get; set; }

        [JsonProperty("SubCustomer")]
        [ForeignKey(nameof(SubCustomerID))]
        public Customers SubCustomer { get; set; }

        [JsonProperty("User")]
        [ForeignKey(nameof(UserID))]
        public Users User { get; set; }

        [JsonProperty("User_InsUser")]
        [ForeignKey(nameof(InsUserID))]
        public Users User_InsUser { get; set; }

        [JsonProperty("User_EditUser")]
        [ForeignKey(nameof(EditUserID))]
        public Users User_EditUser { get; set; }



        [JsonProperty("OrderDetailList")]
        public System.Collections.Generic.List<OrderDetails> OrderDetailList { get; set; }


    }
}