using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;

namespace PPC.Core.Models
{
    [Table("OrderDetail")]
    public class OrderDetails : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("OrderDetailID")]
        [JsonProperty("OrderDetailID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int OrderDetailID { get; set; }

        [Column("OrderID")]
        [JsonProperty("OrderID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int OrderID { get; set; }

        [Column("ProductID")]
        [JsonProperty("ProductID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int ProductID { get; set; }

        [Column("Quantity")]
        [JsonProperty("Quantity")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public decimal Quantity { get; set; }

        [Column("ProgrammedQuantity")]
        [JsonProperty("ProgrammedQuantity")]



        public decimal? ProgrammedQuantity { get; set; }

        [Column("Status")]
        [JsonProperty("Status")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public byte Status { get; set; }

        [Column("ProducedNo")]
        [JsonProperty("ProducedNo")]



        public int? ProducedNo { get; set; }

        [Column("DeliveredNo")]
        [JsonProperty("DeliveredNo")]



        public int? DeliveredNo { get; set; }

        [Column("ProducedWeight")]
        [JsonProperty("ProducedWeight")]



        public decimal? ProducedWeight { get; set; }

        [Column("DeliveredWeight")]
        [JsonProperty("DeliveredWeight")]



        public decimal? DeliveredWeight { get; set; }

        [Column("InPlan")]
        [JsonProperty("InPlan")]



        public decimal? InPlan { get; set; }

        [Column("PackagingPlanID")]
        [JsonProperty("PackagingPlanID")]
        public int? PackagingPlanID { get; set; }

        [Column("Priority")]
        [JsonProperty("Priority")]

        public byte Priority { get; set; }

        [Column("Remark")]
        [JsonProperty("Remark")]

        [MaxLength(1000)]

        public string Remark { get; set; }

        [Column("DeliverDate")]
        [JsonProperty("DeliverDate")]

        [MaxLength(12)]

        public string DeliverDate { get; set; }

        [Column("OrderRequestDetailID")]
        [JsonProperty("OrderRequestDetailID")]



        public int? OrderRequestDetailID { get; set; }

        [Column("PlannedRemain")]
        [JsonProperty("PlannedRemain")]



        public decimal? PlannedRemain { get; set; }

        [Column("WarehouseAmount")]
        [JsonProperty("WarehouseAmount")]
        public decimal? WarehouseAmount { get; set; }

        [Column("ConfirmUserID")]
        [JsonProperty("ConfirmUserID")]
        public int? ConfirmUserID { get; set; }

        [Column("BOMID")]
        [JsonProperty("BOMID")]
        public int? BOMID { get; set; }

        [Column("Radif")]
        [JsonProperty("Radif")]
        public byte Radif { get; set; }


        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("Order")]
        [ForeignKey(nameof(OrderID))]
        public Orders Order { get; set; }

        [JsonProperty("Product")]
        [ForeignKey(nameof(ProductID))]
        public Products Product { get; set; }

        [JsonProperty("PackagingPlan")]
        [ForeignKey(nameof(PackagingPlanID))]
        public PackagingPlans PackagingPlan { get; set; }

        [JsonProperty("ConfirmUser")]
        [ForeignKey(nameof(ConfirmUserID))]
        public Users ConfirmUser { get; set; }

        [JsonProperty("BOM")]
        [ForeignKey(nameof(BOMID))]
        public BOM BOM { get; set; }

        /// <summary>
        /// شناسه طرح بسته بندی - اولویت
        /// </summary>
        [NotMapped]
        [JsonProperty("PackagingPlanIdList")]
        public Dictionary<int, byte> PackagingPlanIdList { get; set; }

        [JsonProperty("OrderDetailPackagingList")]
        public List<OrderDetailPackagings> OrderDetailPackagingList { get; set; }

        [JsonProperty("OrderBOMRevisions")]
        public List<OrderBOMRevisions> OrderBOMRevisions { get; set; }

        [NotMapped]
        [JsonProperty("OrderBOMRevise")]
        public OrderBOMRevisions OrderBOMRevise { get => OrderBOMRevisions?.OrderBy(x => x.OrderBOMReviseID).LastOrDefault(); }


    }
}

/*
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;
using PPC.Response.DTOs;
using System.Collections.Generic;

namespace PPC.Core.Models
{
    [Table("OrderDetail")]
    public class OrderDetails : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("OrderDetailID")]
        [JsonProperty("OrderDetailID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int OrderDetailID { get; set; }

        [Column("OrderID")]
        [JsonProperty("OrderID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int OrderID { get; set; }

        [Column("ProductID")]
        [JsonProperty("ProductID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int ProductID { get; set; }

        [Column("Thickness")]
        [JsonProperty("Thickness")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public byte Thickness { get; set; }

        [Column("InnerDiameter")]
        [JsonProperty("InnerDiameter")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int InnerDiameter { get; set; }

        [Column("OuterDiameter")]
        [JsonProperty("OuterDiameter")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int OuterDiameter { get; set; }

        [Column("Width")]
        [JsonProperty("Width")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public short Width { get; set; }

        [Column("Quantity")]
        [JsonProperty("Quantity")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public decimal Quantity { get; set; }

        [Column("ProgrammedQuantity")]
        [JsonProperty("ProgrammedQuantity")]
        public decimal? ProgrammedQuantity { get; set; }

        [Column("Length")]
        [JsonProperty("Length")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int Length { get; set; }

        [Column("WeightPerRoll")]
        [JsonProperty("WeightPerRoll")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public decimal WeightPerRoll { get; set; }

        [Column("NoOfRolls")]
        [JsonProperty("NoOfRolls")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public decimal NoOfRolls { get; set; }

        [Column("PalletType")]
        [JsonProperty("PalletType")]
        [MaxLength(1)]
        public string PalletType { get; set; }

        [Column("Status")]
        [JsonProperty("Status")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public byte Status { get; set; }

        [Column("ProducedNo")]
        [JsonProperty("ProducedNo")]
        public int? ProducedNo { get; set; }

        [Column("DeliveredNo")]
        [JsonProperty("DeliveredNo")]
        public int? DeliveredNo { get; set; }

        [Column("ProducedWeight")]
        [JsonProperty("ProducedWeight")]
        public decimal? ProducedWeight { get; set; }

        [Column("DeliveredWeight")]
        [JsonProperty("DeliveredWeight")]
        public decimal? DeliveredWeight { get; set; }

        [Column("InPlan")]
        [JsonProperty("InPlan")]
        public decimal? InPlan { get; set; }

        [Column("PackagingPlanID")]
        [JsonProperty("PackagingPlanID")]
        public int? PackagingPlanID { get; set; }

        [Column("Periority")]
        [JsonProperty("Periority")]
        //[Display(Name = "TblAnot_OrderDetail_Periority", ResourceType = typeof(Resources.Resources))]
        public byte? Periority { get; set; }

        [Column("Remark")]
        [JsonProperty("Remark")]
        [MaxLength(1000)]
        public string Remark { get; set; }

        [Column("UnitPrice")]
        [JsonProperty("UnitPrice")]
        public int? UnitPrice { get; set; }

        [Column("DeliverDate")]
        [JsonProperty("DeliverDate")]
        [MaxLength(12)]
        public string DeliverDate { get; set; }

        [Column("OrderRequestDetailID")]
        [JsonProperty("OrderRequestDetailID")]
        public int? OrderRequestDetailID { get; set; }

        [Column("PlannedRemain")]
        [JsonProperty("PlannedRemain")]
        public decimal? PlannedRemain { get; set; }

        [Column("WarehouseAmount")]
        [JsonProperty("WarehouseAmount")]
        public decimal? WarehouseAmount { get; set; }

        [Column("ConfirmUserID")]
        [JsonProperty("ConfirmUserID")]
        public int? ConfirmUserID { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("Order")]
        [ForeignKey(nameof(OrderID))]
        public  Orders Order   { get; set; }

        [JsonProperty("Product")]
        [ForeignKey(nameof(ProductID))]
        public Products Product { get; set; }

        [JsonProperty("PackagingPlan")]
        [ForeignKey(nameof(PackagingPlanID))]
        public PackagingPlans PackagingPlan { get; set; }

        [JsonProperty("ConfirmUser")]
        [ForeignKey(nameof(ConfirmUserID))]
        public  Users ConfirmUser { get; set; }


    }
}
*/