using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("PackagingType")]
    public class PackagingTypes : IEntity
    {
        #region Base properties
        [Key]
        [Column("PackagingTypeID")]
        [JsonProperty("PackagingTypeID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int PackagingTypeID { get; set; }

        [Column("PackagingTypeCode")]
        [JsonProperty("PackagingTypeCode")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string PackagingTypeCode { get; set; }

        [Column("PackagingTypeName")]
        [JsonProperty("PackagingTypeName")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string PackagingTypeName { get; set; }

        [Column("PackagingTypeDesc")]
        [JsonProperty("PackagingTypeDesc")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(150)]

        public string PackagingTypeDesc { get; set; }

        [Column("UnitID")]
        [JsonProperty("UnitID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int UnitID { get; set; }

        [Column("EmptyWeight")]
        [JsonProperty("EmptyWeight")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public decimal EmptyWeight { get; set; }

        [Column("Capacity")]
        [JsonProperty("Capacity")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public decimal Capacity { get; set; }

        [Column("MinCapacity")]
        [JsonProperty("MinCapacity")]



        public decimal? MinCapacity { get; set; }

        [Column("MaxCapacity")]
        [JsonProperty("MaxCapacity")]



        public decimal? MaxCapacity { get; set; }

        [Column("Tolerance")]
        [JsonProperty("Tolerance")]



        public short? Tolerance { get; set; }

        [Column("IsEditableEmptyWeight")]
        [JsonProperty("IsEditableEmptyWeight")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsEditableEmptyWeight { get; set; }

        [Column("UsableInProduction")]
        [JsonProperty("UsableInProduction")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool UsableInProduction { get; set; }

        [Column("PackagingUsableType")]
        [JsonProperty("PackagingUsableType")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public byte PackagingUsableType { get; set; }

        [Column("Describe")]
        [JsonProperty("Describe")]

        [MaxLength(150)]

        public string Describe { get; set; }

        [Column("EditUserID")]
        [JsonProperty("EditUserID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int EditUserID { get; set; }

        [Column("EditDate")]
        [JsonProperty("EditDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string EditDate { get; set; }

        [Column("EditTime")]
        [JsonProperty("EditTime")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]

        public string EditTime { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsActive { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)
    }
}