using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("PrintingTechnique")]
    public class PrintingTechniques : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("PrintingTechniqueID")]
        [JsonProperty("PrintingTechniqueID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public short PrintingTechniqueID { get; set; }

        [Column("PrintingTechniqueName")]
        [JsonProperty("PrintingTechniqueName")]
        public string PrintingTechniqueName { get; set; }

        [Column("PrintingTechniqueLatinName")]
        [JsonProperty("PrintingTechniqueLatinName")]
        public string PrintingTechniqueLatinName { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

    }
}
