using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("ProductSerieTechniqueAssign")]
    public class ProductSerieTechniqueAssigns : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("ProductSerieTechniqueAssignID")]
        [JsonProperty("ProductSerieTechniqueAssignID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int ProductSerieTechniqueAssignID { get; set; }

        [Column("ProductSerieID")]
        [JsonProperty("ProductSerieID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int ProductSerieID { get; set; }

        [Column("PrintingTechniqueID")]
        [JsonProperty("PrintingTechniqueID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public short PrintingTechniqueID { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("ProductSerie")]
        [ForeignKey(nameof(ProductSerieID))]
        public ProductSeries ProductSerie { get; set; }

        [JsonProperty("PrintingTechnique")]
        [ForeignKey(nameof(PrintingTechniqueID))]
        public PrintingTechniques PrintingTechnique { get; set; }

    }
}
