using PPC.Core.Models.Entity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("ProductType")]
    public class ProductTypes : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("ProductTypeID")]
        [JsonProperty("ProductTypeID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

        public short ProductTypeID { get; set; }

        [Column("ProductTypeName")]
        [JsonProperty("ProductTypeName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public string ProductTypeName { get; set; }

        [Column("ProductTypeLatinName")]
        [JsonProperty("ProductTypeLatinName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public string ProductTypeLatinName { get; set; }

        [Column("ProductTypeLabelName")]
        [JsonProperty("ProductTypeLabelName")]

        [MaxLength(30)]

        public string ProductTypeLabelName { get; set; }

        [Column("ProductTypeLabelLatinName")]
        [JsonProperty("ProductTypeLabelLatinName")]

        [MaxLength(30)]

        public string ProductTypeLabelLatinName { get; set; }

        [Column("ProductGroupID")]
        [JsonProperty("ProductGroupID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public short ProductGroupID { get; set; }

        [Column("BOMSerialCode")]
        [JsonProperty("BOMSerialCode")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public string BOMSerialCode { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool IsActive { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("ProductGroup")]
        public ProductGroups ProductGroup { get; set; }
    }
}
