using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;
using PPC.Response.DTOs;

namespace PPC.Core.Models
{
    [Table("Product")]
    public class Products : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("ProductID")]
        [JsonProperty("ProductID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int ProductID { get; set; }

        [Column("ProductCode")]
        [JsonProperty("ProductCode")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public string ProductCode { get; set; }

        [Column("SerialCode")]
        [JsonProperty("SerialCode")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public string SerialCode { get; set; }

        [Column("ProductName")]
        [JsonProperty("ProductName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public string ProductName { get; set; }

        [Column("ProductLatinName")]
        [JsonProperty("ProductLatinName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string ProductLatinName { get; set; }

        [Column("ProductLabelName")]
        [JsonProperty("ProductLabelName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string ProductLabelName { get; set; }

        [Column("ProductLatinLabelName")]
        [JsonProperty("ProductLatinLabelName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string ProductLatinLabelName { get; set; }

        [Column("ProductSerieID")]
        [JsonProperty("ProductSerieID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int ProductSerieID { get; set; }

        [Column("PrintingTechniqueID")]
        [JsonProperty("PrintingTechniqueID")]
        //[Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public Nullable<short> PrintingTechniqueID { get; set; }

        [Column("TestPlanID")]
        [JsonProperty("TestPlanID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int TestPlanID { get; set; }

        [Column("ShelfLifeMonth")]
        [JsonProperty("ShelfLifeMonth")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public short ShelfLifeMonth { get; set; }

        [Column("IsSemiProduct")]
        [JsonProperty("IsSemiProduct")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool IsSemiProduct { get; set; }

        [Column("Final_RawMaterialID")]
        [JsonProperty("Final_RawMaterialID")]
        public int? Final_RawMaterialID { get; set; }

        [Column("Final_ProductID")]
        [JsonProperty("Final_ProductID")]
        public int? Final_ProductID { get; set; }

        [Column("IsPaste")]
        [JsonProperty("IsPaste")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool IsPaste { get; set; }

        [Column("BOMSerialCode")]
        [JsonProperty("BOMSerialCode")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public string BOMSerialCode { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool IsActive { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("ProductSerie")]
        [ForeignKey(nameof(ProductSerieID))]
        public ProductSeries ProductSerie { get; set; }

        [JsonProperty("PrintingTechniques")]
        [ForeignKey(nameof(PrintingTechniqueID))]
        public PrintingTechniques PrintingTechniques { get; set; }


        ///Loooooooooooop
        //[JsonProperty("TestPlanAssign")]
        //[ForeignKey(nameof(TestPlanAssignID))]
        //public TestPlanAssign TestPlanAssign { get; set; }

        [JsonProperty("TestPlan")]
        [ForeignKey(nameof(TestPlanID))]
        public TestPlans TestPlan { get; set; }

        [JsonProperty("Final_RawMaterial")]
        [ForeignKey(nameof(Final_RawMaterialID))]
        public RawMaterials Final_RawMaterial { get; set; }

        [JsonProperty("Final_Product")]
        [ForeignKey(nameof(Final_ProductID))]
        public Products Final_Product { get; set; }

        #region Foreign Keys


        #endregion


        #region Children
        

        #endregion



    }
}