using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("ProductGroupType")]
    public class ProductGroupTypes : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("ProductGroupTypeID")]
        [JsonProperty("ProductGroupTypeID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

        public short ProductGroupTypeID { get; set; }

        [Column("ProductGroupTypeName")]
        [JsonProperty("ProductGroupTypeName")]



        public string ProductGroupTypeName { get; set; }

        [Column("ProductGroupTypeLatinName")]
        [JsonProperty("ProductGroupTypeLatinName")]



        public string ProductGroupTypeLatinName { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsActive { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)

    }
}
