using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("RawMaterialConfirmation")]
    public class RawMaterialConfirmation : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("RawMaterialConfirmationID")]
        [JsonProperty("RawMaterialConfirmationID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int RawMaterialConfirmationID { get; set; }

        [Column("RawMaterialID")]
        [JsonProperty("RawMaterialID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int RawMaterialID { get; set; }


        [Column("Status")]
        [JsonProperty("Status")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public byte Status { get; set; }

        [Column("IsConfirmed")]
        [JsonProperty("IsConfirmed")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsConfirmed { get; set; }

        [Column("InsUserID")]
        [JsonProperty("InsUserID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int InsUserID { get; set; }

        [Column("InsDate")]
        [JsonProperty("InsDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]
        public string InsDate { get; set; }

        [Column("InsTime")]
        [JsonProperty("InsTime")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]
        public string InsTime { get; set; }

        [Column("ConfirmerID")]
        [JsonProperty("ConfirmerID")]



        public int? ConfirmerID { get; set; }

        [Column("ConfirmDate")]
        [JsonProperty("ConfirmDate")]

        [MaxLength(10)]

        public string ConfirmDate { get; set; }

        [Column("ConfirmTime")]
        [JsonProperty("ConfirmTime")]

        [MaxLength(5)]

        public string ConfirmTime { get; set; }

        [Column("ConfirmDescribe")]
        [JsonProperty("ConfirmDescribe")]

        [MaxLength(150)]

        public string ConfirmDescribe { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

    }
}