using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace PPC.Core.Models
{
    [Table("RawMaterial")]
    //[Keyless]

    public class RawMaterials : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("RawMaterialID")]
        [JsonProperty("RawMaterialID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int RawMaterialID { get; set; }

        [Column("RawMaterialOriginCode")]
        [JsonProperty("RawMaterialOriginCode")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public string RawMaterialOriginCode { get; set; }

        [Column("RawMaterialOriginName")]
        [JsonProperty("RawMaterialOriginName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public string RawMaterialOriginName { get; set; }

        [Column("RawMaterialCode")]
        [JsonProperty("RawMaterialCode")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(20)]
        public string RawMaterialCode { get; set; }

        [Column("RawMaterialName")]
        [JsonProperty("RawMaterialName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string RawMaterialName { get; set; }

        [Column("RawMaterialLatinName")]
        [JsonProperty("RawMaterialLatinName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string RawMaterialLatinName { get; set; }

        [Column("UnitID")]
        [JsonProperty("UnitID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int UnitID { get; set; }

        [Column("RawMaterialGroupID")]
        [JsonProperty("RawMaterialGroupID")]
        public short RawMaterialGroupID { get; set; }

        [Column("SupplierID")]
        [JsonProperty("SupplierID")]
        //[Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public short? SupplierID { get; set; }

        [Column("IsRecycled")]
        [JsonProperty("IsRecycled")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsRecycled { get; set; }

        [Column("StorageConditions")]
        [JsonProperty("StorageConditions")]

        [MaxLength(300)]

        public string StorageConditions { get; set; }

        [Column("SolidPercentage")]
        [JsonProperty("SolidPercentage")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [Precision(8, 4)]
        public decimal SolidPercentage { get; set; }


        [Column("IsSample")]
        [JsonProperty("IsSample")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool IsSample { get; set; }

        [Column("IsSemiProduct")]
        [JsonProperty("IsSemiProduct")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool IsSemiProduct { get; set; }

        [Column("HasBOMFormula")]
        [JsonProperty("HasBOMFormula")]
        public bool HasBOMFormula { get; set; } = false;

        [Column("RawMaterialSampleID")]
        [JsonProperty("RawMaterialSampleID")]
        public int? RawMaterialSampleID { get; set; }

        [Column("TestPlanAssignID")]
        [JsonProperty("TestPlanAssignID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int TestPlanAssignID { get; set; }

        //[Column("ParentID")]
        //[JsonProperty("ParentID")]
        ////[Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        //public int? ParentID { get; set; }


        [Column("IsConfirmed")]
        [JsonProperty("IsConfirmed")]
        public bool? IsConfirmed { get; set; }

        [Column("InsUserID")]
        [JsonProperty("InsUserID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int InsUserID { get; set; }

        [Column("InsDate")]
        [JsonProperty("InsDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]
        public string InsDate { get; set; }

        [Column("InsTime")]
        [JsonProperty("InsTime")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]
        public string InsTime { get; set; }


        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool IsActive { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)


        [JsonProperty("RawMaterialGroups")]
        [ForeignKey(nameof(RawMaterialGroupID))]
        public RawMaterialGroups RawMaterialGroups { get; set; }

        [JsonProperty("Units")]
        [ForeignKey(nameof(UnitID))]
        public Units Units { get; set; }

        [JsonProperty("Supplier")]
        [ForeignKey(nameof(SupplierID))]
        public Suppliers Supplier { get; set; }

        [JsonProperty("RawMaterial_Sample")]
        [ForeignKey(nameof(RawMaterialSampleID))]
        public RawMaterials RawMaterial_Sample { get; set; }

        [JsonProperty("TestPlanAssign")]
        [ForeignKey(nameof(TestPlanAssignID))]
        public TestPlanAssign TestPlanAssign { get; set; }

        //[JsonProperty("Parent")]
        //[ForeignKey(nameof(ParentID))]
        //public RawMaterials Parent { get; set; }

        //[NotMapped]
        [JsonProperty("LotNosList")]
        public List<RawMaterialLotNumbers> LotNosList { get; set; } = null;

        //[NotMapped]
        [JsonProperty("RMWhiteListAssign")]
        public List<RawMaterialWhiteListAssign> RMWhiteListAssign { get; set; }

    }
}