using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("RawMaterialGroup")]
    public class RawMaterialGroups : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("RawMaterialGroupID")]
        [JsonProperty("RawMaterialGroupID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

        public short RawMaterialGroupID { get; set; }

        [Column("RawMaterialGroupName")]
        [JsonProperty("RawMaterialGroupName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public string RawMaterialGroupName { get; set; }

        [Column("RawMaterialGroupLatinName")]
        [JsonProperty("RawMaterialGroupLatinName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public string RawMaterialGroupLatinName { get; set; }

        [Column("RawMaterialGroupTypeID")]
        [JsonProperty("RawMaterialGroupTypeID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public short RawMaterialGroupTypeID { get; set; }

        [Column("StorageConditions")]
        [JsonProperty("StorageConditions")]

        [MaxLength(300)]

        public string StorageConditions { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)


        [JsonProperty("RawMaterialGroupType")]
        [ForeignKey(nameof(RawMaterialGroupTypeID))]
        public RawMaterialGroupTypes RawMaterialGroupType { get; set; }


    }
}