using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("RawMaterialWhiteListAssign")]
    public class RawMaterialWhiteListAssign : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("RawMaterialWhiteListAssignID")]
        [JsonProperty("RawMaterialWhiteListAssignID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int RawMaterialWhiteListAssignID { get; set; }

        [Column("RawMaterialID")]
        [JsonProperty("RawMaterialID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int RawMaterialID { get; set; }

        [Column("RMWhiteListID")]
        [JsonProperty("RMWhiteListID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int RMWhiteListID { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("RawMaterial")]
        [ForeignKey(nameof(RawMaterialID))]
        public RawMaterials RawMaterial { get; set; }

        [JsonProperty("RMWhiteList")]
        [ForeignKey(nameof(RMWhiteListID))]
        public RMWhiteLists RMWhiteList { get; set; }



    }
}