using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("RMWhiteLists")]
    public class RMWhiteLists : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("RMWhiteListID")]
        [JsonProperty("RMWhiteListID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int RMWhiteListID { get; set; }

        [Column("RMWhiteListCode")]
        [JsonProperty("RMWhiteListCode")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public string RMWhiteListCode { get; set; }

        [Column("RMWhiteListName")]
        [JsonProperty("RMWhiteListName")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public string RMWhiteListName { get; set; }

        [Column("ProductSerieID")]
        [JsonProperty("ProductSerieID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int ProductSerieID { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("ProductSerie")]
        [ForeignKey(nameof(ProductSerieID))]
        public ProductSeries ProductSerie { get; set; }



    }
}