using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("SaleAgent")]
    public class SaleAgents : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("SaleAgentID")]
        [JsonProperty("SaleAgentID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

        public short SaleAgentID { get; set; }

        [Column("SaleAgentCode")]
        [JsonProperty("SaleAgentCode")]


       //[Display(Name = "TblAnot_SaleAgent_SaleAgentCode", ResourceType = typeof(Resources.Resources))]
        public string SaleAgentCode { get; set; }

        [Column("SaleAgentName")]
        [JsonProperty("SaleAgentName")]


       //[Display(Name = "TblAnot_SaleAgent_SaleAgentName", ResourceType = typeof(Resources.Resources))]
        public string SaleAgentName { get; set; }

        [Column("SaleAgentLatinName")]
        [JsonProperty("SaleAgentLatinName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(100)]
       //[Display(Name = "TblAnot_SaleAgent_SaleAgentLatinName", ResourceType = typeof(Resources.Resources))]
        public string SaleAgentLatinName { get; set; }

        [Column("SaleAgentLocalizedName")]
        [JsonProperty("SaleAgentLocalizedName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(100)]
       //[Display(Name = "TblAnot_SaleAgent_SaleAgentLocalizedName", ResourceType = typeof(Resources.Resources))]
        public string SaleAgentLocalizedName { get; set; }

        [Column("ProvinceID")]
        [JsonProperty("ProvinceID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

       //[Display(Name = "TblAnot_SaleAgent_ProvinceID", ResourceType = typeof(Resources.Resources))]
        public short ProvinceID { get; set; }

        [Column("IsForeign")]
        [JsonProperty("IsForeign")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

       //[Display(Name = "TblAnot_SaleAgent_IsForeign", ResourceType = typeof(Resources.Resources))]
        public bool IsForeign { get; set; }

        [Column("ContactPerson")]
        [JsonProperty("ContactPerson")]

        [MaxLength(50)]
       //[Display(Name = "TblAnot_SaleAgent_ContactPerson", ResourceType = typeof(Resources.Resources))]
        public string ContactPerson { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

       //[Display(Name = "TblAnot_SaleAgent_IsActive", ResourceType = typeof(Resources.Resources))]
        public bool IsActive { get; set; } = true;

        [Column("Rating")]
        [JsonProperty("Rating")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

       //[Display(Name = "TblAnot_SaleAgent_Rating", ResourceType = typeof(Resources.Resources))]
        public decimal Rating { get; set; } = 0;

        [Column("CustomerGradeID")]
        [JsonProperty("CustomerGradeID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

       //[Display(Name = "TblAnot_SaleAgent_CustomerGradeID", ResourceType = typeof(Resources.Resources))]
        public short CustomerGradeID { get; set; }

        [Column("StartDate")]
        [JsonProperty("StartDate")]

        [MaxLength(10)]
       //[Display(Name = "TblAnot_SaleAgent_StartDate", ResourceType = typeof(Resources.Resources))]
        public string StartDate { get; set; }

        [Column("Address")]
        [JsonProperty("Address")]

        [MaxLength(300)]
       //[Display(Name = "TblAnot_SaleAgent_Address", ResourceType = typeof(Resources.Resources))]
        public string Address { get; set; }

        [Column("Tel")]
        [JsonProperty("Tel")]

        [MaxLength(100)]
       //[Display(Name = "TblAnot_SaleAgent_Tel", ResourceType = typeof(Resources.Resources))]
        public string Tel { get; set; }

        [Column("ZipCode")]
        [JsonProperty("ZipCode")]

        [MaxLength(15)]
       //[Display(Name = "TblAnot_SaleAgent_ZipCode", ResourceType = typeof(Resources.Resources))]
        public string ZipCode { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)

        public Provinces Province { get; set; } 
        public CustomerGrades CustomerGrade { get; set; }

    }
}
