using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using WebApi.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;
using System;

namespace WebApi.Core.Models
{
    [Table("Setting")]
    public class Settings : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("SettingID")]
        [JsonProperty("SettingID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int SettingID { get; set; }

        [Column("LastVersion")]
        [JsonProperty("LastVersion")]
        public string LastVersion { get; set; }

        [Column("LastVersionWarninType")]
        [JsonProperty("LastVersionWarninType")]
        public byte LastVersionWarninType { get; set; }

        [Column("UserID")]
        [JsonProperty("UserID")]
        public Nullable<int> UserID { get; set; }

        [Column("StationID")]
        [JsonProperty("StationID")]
        public Nullable<int> StationID { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("User")]
        [ForeignKey(nameof(UserID))]
        public Users User { get; set; }



    }
}