using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("TestPlanGroupTypeAssign")]
    public class TestPlanGroupTypeAssigns : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("TestPlanGroupTypeAssignID")]
        [JsonProperty("TestPlanGroupTypeAssignID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public short TestPlanGroupTypeAssignID { get; set; }

        [Column("TestPlanGroupID")]
        [JsonProperty("TestPlanGroupID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public byte TestPlanGroupID { get; set; }

        [Column("TestPlanEntranceType")]
        [JsonProperty("TestPlanEntranceType")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public byte TestPlanEntranceType { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

    }
}