using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("TestPlanCodeChar")]
    public class TestPlanCodeChar : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("TestPlanCodeCharID")]
        [JsonProperty("TestPlanCodeCharID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public short TestPlanCodeCharID { get; set; }

        [Column("CodeChar")]
        [JsonProperty("CodeChar")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public string CodeChar { get; set; }

        [Column("IsProductType")]
        [JsonProperty("IsProductType")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public bool IsProductType { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)
 
    }
}