using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PPC.Core.Models
{
    [Table("TestPlan")]
    public class TestPlans : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("TestPlanID")]
        [JsonProperty("TestPlanID")]
        public int TestPlanID { get; set; }

        [Column("MaterialTypeID")]
        [JsonProperty("MaterialTypeID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public byte MaterialTypeID { get; set; }


        [Column("ProductTypeID")]
        [JsonProperty("ProductTypeID")]
        public short? ProductTypeID { get; set; }

        [Column("RawMaterialGroupTypeID")]
        [JsonProperty("RawMaterialGroupTypeID")]
        public short? RawMaterialGroupTypeID { get; set; }

        [Column("TestPlanMCode")]
        [JsonProperty("TestPlanMCode")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(4)]
        public string TestPlanMCode { get; set; }

        [Column("TestPlanCode")]
        [JsonProperty("TestPlanCode")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(8)]
        public string TestPlanCode { get; set; }

        [Column("TestPlanCodeChar")]
        [JsonProperty("TestPlanCodeChar")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(1)]
        public string TestPlanCodeChar { get; set; }

        [Column("TestPlanCodeNum")]
        [JsonProperty("TestPlanCodeNum")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(3)]
        public string TestPlanCodeNum { get; set; }

        [Column("TestPlanCodeSeri")]
        [JsonProperty("TestPlanCodeSeri")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(3)]
        public string TestPlanCodeSeri { get; set; }

        [Column("TestPlanCodeVersion")]
        [JsonProperty("TestPlanCodeVersion")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(3)]

        public string TestPlanCodeVersion { get; set; }

        [Column("Version")]
        [JsonProperty("Version")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public short Version { get; set; }

        [Column("InsUserID")]
        [JsonProperty("InsUserID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int InsUserID { get; set; }

        [Column("InsUserName")]
        [JsonProperty("InsUserName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string InsUserName { get; set; }

        [Column("InsUserFullName")]
        [JsonProperty("InsUserFullName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string InsUserFullName { get; set; }

        [Column("InsDate")]
        [JsonProperty("InsDate")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string InsDate { get; set; }

        [Column("InsTime")]
        [JsonProperty("InsTime")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]

        public string InsTime { get; set; }

        [Column("EditUserID")]
        [JsonProperty("EditUserID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int EditUserID { get; set; }

        [Column("EditUserName")]
        [JsonProperty("EditUserName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string EditUserName { get; set; }

        [Column("EditUserFullName")]
        [JsonProperty("EditUserFullName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string EditUserFullName { get; set; }

        [Column("EditDate")]
        [JsonProperty("EditDate")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string EditDate { get; set; }

        [Column("EditTime")]
        [JsonProperty("EditTime")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]

        public string EditTime { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsActive { get; set; }

        [Column("LastNodeID")]
        [JsonProperty("LastNodeID")]
        public int? LastNodeID { get; set; }

        [Column("ParentID")]
        [JsonProperty("ParentID")]
        public int? ParentID { get; set; }

        [Column("Status")]
        [JsonProperty("Status")]
        public byte Status { get; set; }

        [Column("IsConfirmed")]
        [JsonProperty("IsConfirmed")]
        public bool IsConfirmed { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)


        [JsonProperty("ProductGroup")]
        [ForeignKey(nameof(ProductTypeID))]
        public ProductGroups ProductGroup { get; set; }

        [JsonProperty("RawMaterialGroupType")]
        [ForeignKey(nameof(RawMaterialGroupTypeID))]
        public RawMaterialGroupTypes RawMaterialGroupType { get; set; }

        [JsonProperty("User_InsUser")]
        [ForeignKey(nameof(InsUserID))]
        public Users User_InsUser { get; set; }

        [JsonProperty("User_EditUser")]
        [ForeignKey(nameof(EditUserID))]
        public Users User_EditUser { get; set; }

        [JsonProperty("LastNode")]
        [ForeignKey(nameof(LastNodeID))]
        public TestPlans LastNode { get; set; }


        [JsonProperty("Parent")]
        [ForeignKey(nameof(ParentID))]
        public TestPlans Parent { get; set; }

        [JsonProperty("TestPlanDetails")]
        public List<TestPlanDetails> TestPlanDetails { get; set; }

        [JsonProperty("TestPlanAssign")]
        public List<TestPlanAssign> TestPlanAssign { get; set; }



    }
}


/*
#region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("TestPlanID")]
        [JsonProperty("TestPlanID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int TestPlanID { get; set; }

        [Column("MaterialTypeID")]
        [JsonProperty("MaterialTypeID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public byte MaterialTypeID { get; set; }

        [Column("TestPlanGroupID")]
        [JsonProperty("TestPlanGroupID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public byte TestPlanGroupID { get; set; }

        [Column("TestPlanMCode")]
        [JsonProperty("TestPlanMCode")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(12)]

        public string TestPlanMCode { get; set; }

        [Column("TestPlanCodeChar")]
        [JsonProperty("TestPlanCodeChar")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(1)]

        public string TestPlanCodeChar { get; set; }

        [Column("TestPlanCodeNum")]
        [JsonProperty("TestPlanCodeNum")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(3)]

        public string TestPlanCodeNum { get; set; }


        [Column("TestPlanCodeVersion")]
        [JsonProperty("TestPlanCodeVersion")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(3)]

        public string TestPlanCodeVersion { get; set; }

        [Column("Version")]
        [JsonProperty("Version")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [Range(1,999)]
        public short Version { get; set; }

        [Column("InsUserID")]
        [JsonProperty("InsUserID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int InsUserID { get; set; }

        [Column("InsUserName")]
        [JsonProperty("InsUserName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string InsUserName { get; set; }

        [Column("InsUserFullName")]
        [JsonProperty("InsUserFullName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string InsUserFullName { get; set; }

        [Column("InsDate")]
        [JsonProperty("InsDate")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string InsDate { get; set; }

        [Column("InsTime")]
        [JsonProperty("InsTime")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]

        public string InsTime { get; set; }

        [Column("EditUserID")]
        [JsonProperty("EditUserID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int EditUserID { get; set; }

        [Column("EditUserName")]
        [JsonProperty("EditUserName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string EditUserName { get; set; }

        [Column("EditUserFullName")]
        [JsonProperty("EditUserFullName")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string EditUserFullName { get; set; }

        [Column("EditDate")]
        [JsonProperty("EditDate")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string EditDate { get; set; }

        [Column("EditTime")]
        [JsonProperty("EditTime")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]

        public string EditTime { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsActive { get; set; }

        [Column("LastNodeID")]
        [JsonProperty("LastNodeID")]
       //[Display(Name = "TblAnot_TestPlan_LastNodeID", ResourceType = typeof(Resources.Resources))]
        public Nullable<int> LastNodeID { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator) */