using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PPC.Core.Models
{
    [Table("TestPlanAssign")]
    public class TestPlanAssign : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("TestPlanAssignID")]
        [JsonProperty("TestPlanAssignID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int TestPlanAssignID { get; set; }

        [Column("MaterialTypeID")]
        [JsonProperty("MaterialTypeID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public byte MaterialTypeID { get; set; }

        [Column("ProductID")]
        [JsonProperty("ProductID")]
        public int? ProductID { get; set; }

        [Column("RawMaterialGroupTypeID")]
        [JsonProperty("RawMaterialGroupTypeID")]
        public short? RawMaterialGroupTypeID { get; set; }

        [Column("TestPlanID")]
        [JsonProperty("TestPlanID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int TestPlanID { get; set; }

        [Column("TestPlanAssignedCode")]
        [JsonProperty("TestPlanAssignedCode")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(12)]

        public string TestPlanAssignedCode { get; set; }

        [Column("AssignedCodeNum")]
        [JsonProperty("AssignedCodeNum")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public short AssignedCodeNum { get; set; }

        [Column("Version")]
        [JsonProperty("Version")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public short Version { get; set; }

        [Column("InsUserID")]
        [JsonProperty("InsUserID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int InsUserID { get; set; }

        [Column("InsUserName")]
        [JsonProperty("InsUserName")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string InsUserName { get; set; }

        [Column("InsUserFullName")]
        [JsonProperty("InsUserFullName")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string InsUserFullName { get; set; }

        [Column("InsDate")]
        [JsonProperty("InsDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string InsDate { get; set; }

        [Column("InsTime")]
        [JsonProperty("InsTime")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]

        public string InsTime { get; set; }

        [Column("EditUserID")]
        [JsonProperty("EditUserID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int EditUserID { get; set; }

        [Column("EditUserName")]
        [JsonProperty("EditUserName")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string EditUserName { get; set; }

        [Column("EditUserFullName")]
        [JsonProperty("EditUserFullName")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(50)]

        public string EditUserFullName { get; set; }

        [Column("EditDate")]
        [JsonProperty("EditDate")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(10)]

        public string EditDate { get; set; }

        [Column("EditTime")]
        [JsonProperty("EditTime")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(5)]

        public string EditTime { get; set; }

        [Column("IsActive")]
        [JsonProperty("IsActive")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]


        public bool IsActive { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("Product")]
        [ForeignKey(nameof(ProductID))]
        public Products Product { get; set; }

        [JsonProperty("RawMaterialGroupType")]
        [ForeignKey(nameof(RawMaterialGroupTypeID))]
        public RawMaterialGroupTypes RawMaterialGroupType { get; set; }

        [JsonProperty("TestPlan")]
        [ForeignKey(nameof(TestPlanID))]
        public TestPlans TestPlan { get; set; }

        [JsonProperty("User_InsUser")]
        [ForeignKey(nameof(InsUserID))]
        public Users User_InsUser { get; set; }

        [JsonProperty("User_EditUser")]
        [ForeignKey(nameof(EditUserID))]
        public Users User_EditUser { get; set; }

        //[NotMapped]
        [JsonProperty("TestPlanAssignDetails")]
        public List<TestPlanAssignDetail> TestPlanAssignDetails { get; set; }




    }
}