using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("TestPlanAssignDetail")]
    public class TestPlanAssignDetail : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("TestPlanAssignDetailID")]
        [JsonProperty("TestPlanAssignDetailID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int TestPlanAssignDetailID { get; set; }

        [Column("TestPlanAssignID")]
        [JsonProperty("TestPlanAssignID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int TestPlanAssignID { get; set; }

        [Column("TestPlanIndexID")]
        [JsonProperty("TestPlanIndexID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int TestPlanIndexID { get; set; }

        [Column("MinVal")]
        [JsonProperty("MinVal")]
        public decimal? MinVal { get; set; }

        [Column("MaxVal")]
        [JsonProperty("MaxVal")]
        public decimal? MaxVal { get; set; }

        [Column("TextPhrase")]
        [JsonProperty("TextPhrase")]
        [MaxLength(100)]
        public string TextPhrase { get; set; }

        [Column("UnitID")]
        [JsonProperty("UnitID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public int UnitID { get; set; }

        [Column("DiagnosisMethod")]
        [JsonProperty("DiagnosisMethod")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(30)]
        public string DiagnosisMethod { get; set; }

        [Column("TestTool")]
        [JsonProperty("TestTool")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(30)]
        public string TestTool { get; set; }

        [Column("TestStage")]
        [JsonProperty("TestStage")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        [MaxLength(30)]
        public string TestStage { get; set; }

        [Column("InstructionID")]
        [JsonProperty("InstructionID")]
        [Required(ErrorMessageResourceName = "pub_RequiredField", ErrorMessageResourceType = typeof(Resources.Resources))]
        public short InstructionID { get; set; }

        [Column("Describe")]
        [JsonProperty("Describe")]
        [MaxLength(100)]
        public string Describe { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("TestPlanAssign")]
        [ForeignKey(nameof(TestPlanAssignID))]
        public TestPlanAssign TestPlanAssign { get; set; }

        [JsonProperty("TestPlanIndex")]
        [ForeignKey(nameof(TestPlanIndexID))]
        public TestPlanIndexes TestPlanIndex { get; set; }

        [JsonProperty("Unit")]
        [ForeignKey(nameof(UnitID))]
        public Units Unit { get; set; }

        [JsonProperty("Instruction")]
        [ForeignKey(nameof(InstructionID))]
        public Instructions Instruction { get; set; }


    }
}