using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using PPC.Core.Models.Entity;
using System.ComponentModel;
using Newtonsoft.Json;

namespace PPC.Core.Models
{
    [Table("UserGroupStation")]
    public class UserGroupStations : IEntity
    {
        #region Base properties and methods(generated by  CodeGenerator)
        [Key]
        [Column("UserGroupStationID")]
        [JsonProperty("UserGroupStationID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]

        public int UserGroupStationID { get; set; }

        [Column("UserGroupID")]
        [JsonProperty("UserGroupID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int UserGroupID { get; set; }

        [Column("StationID")]
        [JsonProperty("StationID")]
        [Required(ErrorMessageResourceName = "RequiredField_Anot", ErrorMessageResourceType = typeof(Resources.Resources))]


        public int StationID { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)
    }
}