using Newtonsoft.Json;
namespace WebApi.Response.DTOs
{
    public class AutoCompleteFieldDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("AutoCompleteFieldID")]
        public int AutoCompleteFieldID { get; set; }

        [JsonProperty("FieldName")]
        public string FieldName { get; set; }

        [JsonProperty("FieldValue")]
        public string FieldValue { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)
    }
}