using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class BOMComplementaryDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("BOMComplementaryID")]
        public int BOMComplementaryID { get; set; }

        [JsonProperty("BOMDetailID")]
        public int BOMDetailID { get; set; }

        [JsonProperty("RawMaterialID")]
        public int RawMaterialID { get; set; }

        [JsonProperty("Priority")]
        public decimal Priority { get; set; }

        [JsonProperty("Percentage")]
        public decimal Percentage { get; set; }

        [JsonProperty("Describe")]
        public string Describe { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("BOMDetail")]
        public BOMDetailDTO BOMDetail { get; set; }

        [JsonProperty("RawMaterial")]
        public RawMaterialsDTO RawMaterial { get; set; }



    }
}