using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;

namespace PPC.Response.DTOs
{
    public class BOMDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("BOMID")]
        public int BOMID { get; set; }

        [JsonProperty("BOMCode")]
        public string BOMCode { get; set; }

        [JsonProperty("ProductID")]
        public int ProductID { get; set; }

        [JsonProperty("Status")]
        public byte Status { get; set; }

        [JsonProperty("Version")]
        public short Version { get; set; }

        [JsonProperty("ParentID")]
        public int? ParentID { get; set; }

        [JsonProperty("IsMainBOM")]
        public bool IsMainBOM { get; set; }

        [JsonProperty("Describe")]
        public string Describe { get; set; }

        [JsonProperty("Ver")]
        public short Ver { get; set; }

        [JsonProperty("CustomerVer")]
        public short CustomerVer { get; set; }

        [JsonProperty("InsUserID")]
        public int InsUserID { get; set; }

        [JsonProperty("InsUserName")]
        public string InsUserName { get; set; }

        [JsonProperty("InsUserFullName")]
        public string InsUserFullName { get; set; }

        [JsonProperty("InsDate")]
        public string InsDate { get; set; }

        [JsonProperty("InsTime")]
        public string InsTime { get; set; }

        [JsonProperty("IsDraft")]
        public bool IsDraft { get; set; }

        [JsonProperty("EditUserID")]
        public int EditUserID { get; set; }

        [JsonProperty("EditUserName")]
        public string EditUserName { get; set; }

        [JsonProperty("EditUserFullName")]
        public string EditUserFullName { get; set; }

        [JsonProperty("EditDate")]
        public string EditDate { get; set; }

        [JsonProperty("EditTime")]
        public string EditTime { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)


        [JsonProperty("Product")]
        public ProductsDTO Product { get; set; }

        [JsonProperty("Parent")]
        public BOMDTO Parent { get; set; }

        [JsonProperty("User_InsUser")]
        public UsersDTO User_InsUser { get; set; }

        [JsonProperty("User_EditUser")]
        public UsersDTO User_EditUser { get; set; }

        [JsonProperty("CustomerDossierList")]
        public List<CustomerDossierDTO> CustomerDossierList { get; set; }

        [JsonProperty("CustomerDossierBOMList")]
        public List<CustomerDossierBOMsDTO> CustomerDossierBOMList { get; set; }

        //[JsonProperty("CustomerDossier")]
        //public CustomerDossierDTO CustomerDossier { get => CustomerDossierList?.FirstOrDefault(); }

        [JsonProperty("BOMDetailList")]
        public List<BOMDetailDTO> BOMDetailList { get; set; }

    }
}