using Newtonsoft.Json;
using System.Collections.Generic;

namespace PPC.Response.DTOs
{
    public class BOMDetailDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("BOMDetailID")]
        public int BOMDetailID { get; set; }

        [JsonProperty("BOMID")]
        public int BOMID { get; set; }

        [JsonProperty("RawMaterialID")]
        public int RawMaterialID { get; set; }

        [JsonProperty("RMWhiteListID")]
        public int RMWhiteListID { get; set; }

        [JsonProperty("Priority")]
        public string Priority { get; set; }

        [JsonProperty("Percentage")]
        public decimal? Percentage { get; set; }

        [JsonProperty("IsFinalRM")]
        public bool IsFinalRM { get; set; }

        [JsonProperty("Describe")]
        public string Describe { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)


        [JsonProperty("BOM")]
        public BOMDTO BOM { get; set; }

        [JsonProperty("RawMaterial")]
        public RawMaterialsDTO RawMaterial { get; set; }

        [JsonProperty("RMWhiteList")]
        public RMWhiteListsDTO RMWhiteList { get; set; }

        [JsonProperty("BOMComplementaryList")]
        public List<BOMComplementaryDTO> BOMComplementaryList { get; set; }


    }
}