using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class CustomerDossierBOMsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("CustomerDossierBOMID")]
        public int CustomerDossierBOMID { get; set; }

        [JsonProperty("CustomerDossierID")]
        public int CustomerDossierID { get; set; }

        [JsonProperty("BOMID")]
        public int BOMID { get; set; }

        [JsonProperty("StartDate")]
        public string StartDate { get; set; }

        [JsonProperty("StartTime")]
        public string StartTime { get; set; }

        [JsonProperty("EndDate")]
        public string EndDate { get; set; }

        [JsonProperty("EndTime")]
        public string EndTime { get; set; }

        [JsonProperty("Ver")]
        public short Ver { get; set; }

        [JsonProperty("SerialNumber")]
        public int SerialNumber { get; set; }

        [JsonProperty("Describe")]
        public string Describe { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)


        [JsonProperty("CustomerDossier")]
        public CustomerDossierDTO CustomerDossier { get; set; }

        [JsonProperty("BOM")]
        public BOMDTO BOM { get; set; }


    }
}