using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class DensityOfProductsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("DensityID")]
        public int DensityID { get; set; }

        [JsonProperty("ProductID")]
        public int ProductID { get; set; }

        [JsonProperty("Density")]
        public decimal Density { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("Product")]
        public ProductsDTO Product { get; set; }

    }
}