using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class InstructionsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("InstructionID")]
        public short InstructionID { get; set; }

        [JsonProperty("InstructionCode")]
        public string InstructionCode { get; set; }

        [JsonProperty("InstructionName")]
        public string InstructionName { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)
    }
}