using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class InvRawMaterialLotsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
       
        
        public int InvRawMaterialLotID { get; set; }

        public string LotNo { get; set; }

        public bool IsGenerated { get; set; }

        public string ProducedDate { get; set; }

        public string EnProducedDate { get; set; }

        public string ExpireDate { get; set; }

        public string EnExpireDate { get; set; }

        public string ShelfLife { get; set; }

        public string EnShelfLife { get; set; }

        public decimal SolidPercentage { get; set; }

        public byte QcStatus { get; set; }

        public byte RNDStatus { get; set; }

        public decimal Weight { get; set; }

        public decimal NetWeight { get; set; }

        public string Describe { get; set; }

        public short PalletQty { get; set; }


        #endregion Base properties and methods(generated by  CodeGenerator)


        #region Foreign Keys

        #region RawMaterial


        public int RawMaterialID { get; set; }

        /// <summary>
        /// RawMaterial is parent of this
        /// </summary>
        public virtual RawMaterialsDTO RawMaterial { get; set; }


        #endregion


        #region PackagingType

        public int PackagingTypeID { get; set; }

        /// <summary>
        /// PackagingType is parent of this
        /// </summary>
        public virtual PackagingTypesDTO PackagingType { get; set; }


        #endregion


        #region InvRawMaterials


        public int InvRawMaterialID { get; set; }

        public InvRawMaterialsDTO InvRawMaterial { get; set; }

        #endregion


        #endregion




        #region Children

        #endregion

    }
}