using Newtonsoft.Json;
using System.Collections.Generic;

namespace PPC.Response.DTOs
{
    public class InvRawMaterialsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)


        public int InvRawMaterialID { get; set; }

        public int RawMaterialID { get; set; }

        public string FinancialRequestNo { get; set; }

        public int? InvProductID { get; set; }

        public string EntryDate { get; set; }

        public short? SupplierID { get; set; }

        public string Describe { get; set; }

        public bool IsSample { get; set; }

        public byte Status { get; set; }

        public int InsUserID { get; set; }

        public string InsDate { get; set; }

        public string InsTime { get; set; }

        public int EditUserID { get; set; }

        public string EditDate { get; set; }

        public string EditTime { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)


        public RawMaterialsDTO RawMaterial { get; set; }

        public PackagingTypesDTO PackagingType { get; set; }

        public SuppliersDTO Supplier { get; set; }

        public InvProductsDTO InvProduct { get; set; }


        public UsersDTO User_InsUser { get; set; }

        public UsersDTO User_EditUser { get; set; }

        public Dictionary<string, bool> LotNumbers { get; set; }




        #region Foreign Keys


        #endregion


        #region Children

        #region InvRawMaterialLots


        /// <summary>
        /// List<InvRawMaterialLotsDTO>
        /// </summary>
        public virtual List<InvRawMaterialLotsDTO> InvRawMaterialLotsList { get; set; }

        #endregion

        #endregion

    }
}