using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class MenuAccessStatesDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("MenuAccessStateID")]
        public int MenuAccessStateID { get; set; }

        [JsonProperty("MenuName")]
        public string MenuName { get; set; }

        [JsonProperty("MenuText")]
        public string MenuText { get; set; }

        [JsonProperty("State")]
        public decimal State { get; set; }

        [JsonProperty("MenuGroupID")]
        public byte MenuGroupID { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)
    }
}