using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class OrderDetailPackagingsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("OrderDetailPackagingID")]
        public int OrderDetailPackagingID { get; set; }

        [JsonProperty("OrderDetailID")]
        public int OrderDetailID { get; set; }

        [JsonProperty("PackagingPlanID")]
        public int PackagingPlanID { get; set; }

        [JsonProperty("Priority")]
        public byte Priority { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)
    }
}