using Newtonsoft.Json;
using System.Collections.Generic;

namespace PPC.Response.DTOs
{
    public class OrderDetailsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("OrderDetailID")]
        public int OrderDetailID { get; set; }

        [JsonProperty("OrderID")]
        public int OrderID { get; set; }

        [JsonProperty("ProductID")]
        public int ProductID { get; set; }

        [JsonProperty("Quantity")]
        public decimal Quantity { get; set; }

        [JsonProperty("ProgrammedQuantity")]
        public decimal? ProgrammedQuantity { get; set; }

        [JsonProperty("Status")]
        public byte Status { get; set; }

        [JsonProperty("ProducedNo")]
        public int? ProducedNo { get; set; }

        [JsonProperty("DeliveredNo")]
        public int? DeliveredNo { get; set; }

        [JsonProperty("ProducedWeight")]
        public decimal? ProducedWeight { get; set; }

        [JsonProperty("DeliveredWeight")]
        public decimal? DeliveredWeight { get; set; }

        [JsonProperty("InPlan")]
        public decimal? InPlan { get; set; }

        [JsonProperty("PackagingPlanID")]
        public int? PackagingPlanID { get; set; }

        [JsonProperty("Priority")]
        public byte Priority { get; set; }

        [JsonProperty("Remark")]
        public string Remark { get; set; }

        [JsonProperty("DeliverDate")]
        public string DeliverDate { get; set; }

        [JsonProperty("OrderRequestDetailID")]
        public int? OrderRequestDetailID { get; set; }

        [JsonProperty("PlannedRemain")]
        public decimal? PlannedRemain { get; set; }

        [JsonProperty("WarehouseAmount")]
        public decimal? WarehouseAmount { get; set; }

        [JsonProperty("ConfirmUserID")]
        public int? ConfirmUserID { get; set; }

        [JsonProperty("BOMID")]
        public int? BOMID { get; set; }

        [JsonProperty("Radif")]
        public byte Radif { get; set; }


        #endregion Base properties and methods(generated by  CodeGenerator)


        [JsonProperty("Order")]
        public OrdersDTO Order { get; set; }

        [JsonProperty("Product")]
        public ProductsDTO Product { get; set; }

        [JsonProperty("PackagingPlan")]
        public PackagingPlansDTO PackagingPlan { get; set; }

        [JsonProperty("ConfirmUser")]
        public UsersDTO ConfirmUser { get; set; }

        [JsonProperty("BOM")]
        public BOMDTO BOM { get; set; }

        [JsonProperty("PackagingPlanIdList")]
        public Dictionary<int, byte> PackagingPlanIdList { get; set; }

        [JsonProperty("OrderDetailPackagingList")]
        public List<OrderDetailPackagingsDTO> OrderDetailPackagingList { get; set; }

        [JsonProperty("OrderBOMRevisions")]
        public List<OrderBOMRevisionsDTO> OrderBOMRevisions { get; set; }

        [JsonProperty("OrderBOMRevise")]
        public OrderBOMRevisionsDTO OrderBOMRevise { get; set; }


    }
}




/*
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PPC.Response.DTOs
{
    public class OrderDetailsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("OrderDetailID")]
        public int OrderDetailID { get; set; }

        [JsonProperty("OrderID")]
        public int OrderID { get; set; }

        [JsonProperty("ProductID")]
        public int ProductID { get; set; }

        [JsonProperty("Thickness")]
        public byte Thickness { get; set; }

        [JsonProperty("InnerDiameter")]
        public int InnerDiameter { get; set; }

        [JsonProperty("OuterDiameter")]
        public int OuterDiameter { get; set; }

        [JsonProperty("Width")]
        public short Width { get; set; }

        [JsonProperty("Quantity")]
        public decimal Quantity { get; set; }

        [JsonProperty("ProgrammedQuantity")]
        public decimal? ProgrammedQuantity { get; set; }

        [JsonProperty("Length")]
        public int Length { get; set; }

        [JsonProperty("WeightPerRoll")]
        public decimal WeightPerRoll { get; set; }

        [JsonProperty("NoOfRolls")]
        public decimal NoOfRolls { get; set; }

        [JsonProperty("PalletType")]
        public string PalletType { get; set; }

        [JsonProperty("Status")]
        public byte Status { get; set; }

        [JsonProperty("ProducedNo")]
        public int? ProducedNo { get; set; }

        [JsonProperty("DeliveredNo")]
        public int? DeliveredNo { get; set; }

        [JsonProperty("ProducedWeight")]
        public decimal? ProducedWeight { get; set; }

        [JsonProperty("DeliveredWeight")]
        public decimal? DeliveredWeight { get; set; }

        [JsonProperty("InPlan")]
        public decimal? InPlan { get; set; }

        [JsonProperty("PackagingPlanID")]
        public int? PackagingPlanID { get; set; }

        [JsonProperty("Periority")]
        public byte? Periority { get; set; }

        [JsonProperty("Remark")]
        public string Remark { get; set; }

        [JsonProperty("UnitPrice")]
        public int? UnitPrice { get; set; }

        [JsonProperty("DeliverDate")]
        public string DeliverDate { get; set; }

        [JsonProperty("OrderRequestDetailID")]
        public int? OrderRequestDetailID { get; set; }

        [JsonProperty("PlannedRemain")]
        public decimal? PlannedRemain { get; set; }

        [JsonProperty("WarehouseAmount")]
        public decimal? WarehouseAmount { get; set; }

        [JsonProperty("ConfirmUserID")]
        public int? ConfirmUserID { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)



        [JsonProperty("Order")]
        public OrdersDTO Order { get; set; }

        [JsonProperty("Product")]
        public ProductsDTO Product { get; set; }

        [JsonProperty("PackagingPlan")]
        public PackagingPlansDTO PackagingPlan { get; set; }

        [JsonProperty("ConfirmUser")]
        public UsersDTO ConfirmUser { get; set; }

    }
}

*/