using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class OrdersDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("OrderID")]
        public int OrderID { get; set; }

        [JsonProperty("OrderNo")]
        public string OrderNo { get; set; }

        [JsonProperty("CustomerID")]
        public int CustomerID { get; set; }

        [JsonProperty("SubCustomerID")]
        public int SubCustomerID { get; set; }

        [JsonProperty("ConfirmDate")]
        public string ConfirmDate { get; set; }

        [JsonProperty("CustomerByeNomber")]
        public string CustomerByeNomber { get; set; }

        [JsonProperty("Remark")]
        public string Remark { get; set; }

        [JsonProperty("Tolerance")]
        public byte Tolerance { get; set; }

        [JsonProperty("DeliverFromDate")]
        public string DeliverFromDate { get; set; }

        [JsonProperty("DeliverToDate")]
        public string DeliverToDate { get; set; }

        [JsonProperty("DeliveredDate")]
        public string DeliveredDate { get; set; }

        [JsonProperty("RegisterDate")]
        public string RegisterDate { get; set; }

        [JsonProperty("Status")]
        public byte Status { get; set; }

        [JsonProperty("IsSample")]
        public bool IsSample { get; set; }

        [JsonProperty("DeliverySample")]
        public bool DeliverySample { get; set; }

        [JsonProperty("DeliveryTestReport")]
        public bool DeliveryTestReport { get; set; }

        [JsonProperty("PestControlCertificate")]
        public bool PestControlCertificate { get; set; }

        [JsonProperty("IsPlanningOrder")]
        public bool IsPlanningOrder { get; set; }

        [JsonProperty("PaymentMethod")]
        public string PaymentMethod { get; set; }

        [JsonProperty("SendingReason")]
        public string SendingReason { get; set; }

        [JsonProperty("CustomerIndustry")]
        public string CustomerIndustry { get; set; }

        [JsonProperty("UserID")]
        public int UserID { get; set; }

        [JsonProperty("OrderType")]
        public byte? OrderType { get; set; }

        [JsonProperty("InsUserID")]
        public int InsUserID { get; set; }

        [JsonProperty("InsUserName")]
        public string InsUserName { get; set; }

        [JsonProperty("InsUserFullName")]
        public string InsUserFullName { get; set; }

        [JsonProperty("InsDate")]
        public string InsDate { get; set; }

        [JsonProperty("InsTime")]
        public string InsTime { get; set; }

        [JsonProperty("EditUserID")]
        public int EditUserID { get; set; }

        [JsonProperty("EditUserName")]
        public string EditUserName { get; set; }

        [JsonProperty("EditUserFullName")]
        public string EditUserFullName { get; set; }

        [JsonProperty("EditDate")]
        public string EditDate { get; set; }

        [JsonProperty("EditTime")]
        public string EditTime { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("Customer")]
        public CustomersDTO Customer { get; set; }


        [JsonProperty("SubCustomer")]
        public CustomersDTO SubCustomer { get; set; }

        [JsonProperty("User")]
        public UsersDTO User { get; set; }

        [JsonProperty("User_InsUser")]
        public UsersDTO User_InsUser { get; set; }

        [JsonProperty("User_EditUser")]
        public UsersDTO User_EditUser { get; set; }


        [JsonProperty("OrderDetailList")]
        public System.Collections.Generic.List<OrderDetailsDTO> OrderDetailList { get; set; }


    }
}
