using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class PackagingPlansDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("PackagingPlanID")]
        public int PackagingPlanID { get; set; }

        [JsonProperty("PackagingPlanCode")]
        public string PackagingPlanCode { get; set; }

        [JsonProperty("PackagingPlanName")]
        public string PackagingPlanName { get; set; }

        [JsonProperty("PackagingPlanDesc")]
        public string PackagingPlanDesc { get; set; }

        [JsonProperty("Capacity")]
        public decimal Capacity { get; set; }

        [JsonProperty("EmptyWeight")]
        public decimal EmptyWeight { get; set; }

        [JsonProperty("MinCapacity")]
        public decimal? MinCapacity { get; set; }

        [JsonProperty("Tolerance")]
        public short? Tolerance { get; set; }

        [JsonProperty("Describe")]
        public string Describe { get; set; }

        [JsonProperty("EditUserID")]
        public int EditUserID { get; set; }

        [JsonProperty("EditDate")]
        public string EditDate { get; set; }

        [JsonProperty("EditTime")]
        public string EditTime { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

    }
}