using Newtonsoft.Json;
using System.Collections.Generic;
namespace PPC.Response.DTOs
{
    public class PackagingTypesDTO
    {

        #region Base properties
        [JsonProperty("PackagingTypeID")]
        public int PackagingTypeID { get; set; }

        [JsonProperty("PackagingTypeCode")]
        public string PackagingTypeCode { get; set; }

        [JsonProperty("PackagingTypeName")]
        public string PackagingTypeName { get; set; }

        [JsonProperty("PackagingTypeDesc")]
        public string PackagingTypeDesc { get; set; }

        [JsonProperty("UnitID")]
        public int UnitID { get; set; }

        [JsonProperty("EmptyWeight")]
        public decimal EmptyWeight { get; set; }

        [JsonProperty("Capacity")]
        public decimal Capacity { get; set; }

        [JsonProperty("MinCapacity")]
        public decimal? MinCapacity { get; set; }

        [JsonProperty("MaxCapacity")]
        public decimal? MaxCapacity { get; set; }

        [JsonProperty("Tolerance")]
        public short? Tolerance { get; set; }

        [JsonProperty("IsEditableEmptyWeight")]
        public bool IsEditableEmptyWeight { get; set; }

        [JsonProperty("UsableInProduction")]
        public bool UsableInProduction { get; set; }

        [JsonProperty("PackagingUsableType")]
        public byte PackagingUsableType { get; set; }

        [JsonProperty("Describe")]
        public string Describe { get; set; }

        [JsonProperty("EditUserID")]
        public int EditUserID { get; set; }

        [JsonProperty("EditDate")]
        public string EditDate { get; set; }

        [JsonProperty("EditTime")]
        public string EditTime { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)

    }
}