using System;
using System.Collections.Generic;
using System.Text;

using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class ProductGroupsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("ProductGroupID")]
        public short ProductGroupID { get; set; }

        [JsonProperty("ProductGroupName")]
        public string ProductGroupName { get; set; }

        [JsonProperty("ProductGroupLatinName")]
        public string ProductGroupLatinName { get; set; }

        [JsonProperty("ProductGroupTypeID")]
        public short ProductGroupTypeID { get; set; }

        [JsonProperty("BOMSerialCode")]
        public string BOMSerialCode { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)


        [JsonProperty("ProductGroupType")]
        public ProductGroupTypesDTO ProductGroupType { get; set; }

    }
}
