using System;
using System.Collections.Generic;
using System.Resources;
using System.Text;

using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class ProductTypesDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("ProductTypeID")]
        public short ProductTypeID { get; set; }

        [JsonProperty("ProductTypeName")]
        public string ProductTypeName { get; set; }

        [JsonProperty("ProductTypeLatinName")]
        public string ProductTypeLatinName { get; set; }

        [JsonProperty("ProductTypeLabelName")]
        public string ProductTypeLabelName { get; set; }

        [JsonProperty("ProductTypeLabelLatinName")]
        public string ProductTypeLabelLatinName { get; set; }

        [JsonProperty("ProductGroupID")]
        public short ProductGroupID { get; set; }

        [JsonProperty("BOMSerialCode")]
        public string BOMSerialCode { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("ProductGroup")]
        public ProductGroupsDTO ProductGroup { get; set; }

    }
}
