using System;
using System.Collections.Generic;
using System.Text;

using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class ProductsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("ProductID")]
        public int ProductID { get; set; }

        [JsonProperty("ProductCode")]
        public string ProductCode { get; set; }

        [JsonProperty("SerialCode")]
        public string SerialCode { get; set; }

        [JsonProperty("ProductName")]
        public string ProductName { get; set; }

        [JsonProperty("ProductLatinName")]
        public string ProductLatinName { get; set; }

        [JsonProperty("ProductLabelName")]
        public string ProductLabelName { get; set; }

        [JsonProperty("ProductLatinLabelName")]
        public string ProductLatinLabelName { get; set; }

        [JsonProperty("ProductSerieID")]
        public int ProductSerieID { get; set; }

        [JsonProperty("PrintingTechniqueID")]
        public short? PrintingTechniqueID { get; set; }

        [JsonProperty("TestPlanID")]
        public int TestPlanID { get; set; }

        [JsonProperty("ShelfLifeMonth")]
        public short ShelfLifeMonth { get; set; }

        [JsonProperty("IsSemiProduct")]
        public bool IsSemiProduct { get; set; }

        [JsonProperty("Final_RawMaterialID")]
        public int? Final_RawMaterialID { get; set; }

        [JsonProperty("Final_ProductID")]
        public int? Final_ProductID { get; set; }

        [JsonProperty("BOMSerialCode")]
        public string BOMSerialCode { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }

        [JsonProperty("IsPaste")]
        public bool IsPaste { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("ProductSerie")]
        public ProductSeriesDTO ProductSerie { get; set; }

        [JsonProperty("PrintingTechniques")]
        public PrintingTechniquesDTO PrintingTechniques { get; set; }

        //[JsonProperty("TestPlanAssign")]
        //public TestPlanAssignDTO TestPlanAssign { get; set; }

        [JsonProperty("TestPlan")]
        public TestPlansDTO TestPlan { get; set; }


        [JsonProperty("Final_RawMaterial")]
        public RawMaterialsDTO Final_RawMaterial { get; set; }

        [JsonProperty("Final_Product")]
        public ProductsDTO Final_Product { get; set; }


        #region Foreign Keys


        #endregion


        #region Children
        #region RevertProducts


        /// <summary>
        /// List<Product>
        /// </summary>
        public virtual List<RevertProductsDTO>? RevertProductsList { get; set; }

        #endregion

        #endregion

    }
}
