using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PPC.Response.DTOs
{
    public class RawMaterialsDTO
    {
        #region Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("RawMaterialID")]
        public int RawMaterialID { get; set; }

        [JsonProperty("RawMaterialOriginCode")]
        public string RawMaterialOriginCode { get; set; }

        [JsonProperty("RawMaterialOriginName")]
        public string RawMaterialOriginName { get; set; }

        [JsonProperty("RawMaterialCode")]
        public string RawMaterialCode { get; set; }

        [JsonProperty("RawMaterialName")]
        public string RawMaterialName { get; set; }

        [JsonProperty("RawMaterialLatinName")]
        public string RawMaterialLatinName { get; set; }

        [JsonProperty("UnitID")]
        public UnitsDTO UnitDTO { get; set; }

        [JsonProperty("RawMaterialGroupID")]
        public RawMaterialGroupsDTO RawMaterialGroupsDTO { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)

        //[JsonProperty("UnitID")]
        //public UnitsDTO UnitDTO { get; set; }

        //[JsonProperty("RawMaterialGroupID")]
        //public RawMaterialGroupsDTO RawMaterialGroupsDTO { get; set; }




    }
}
