using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class RawMaterialWhiteListAssignDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("RawMaterialWhiteListAssignID")]
        public int RawMaterialWhiteListAssignID { get; set; }

        [JsonProperty("RawMaterialID")]
        public int RawMaterialID { get; set; }

        [JsonProperty("RMWhiteListID")]
        public int RMWhiteListID { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)


        [JsonProperty("RawMaterial")]
        public RawMaterialsDTO RawMaterial { get; set; }

        [JsonProperty("RMWhiteList")]
        public RMWhiteListsDTO RMWhiteList { get; set; }

    }
}