using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class RawMaterialConfirmationDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("RawMaterialConfirmationID")]
        public int RawMaterialConfirmationID { get; set; }

        [JsonProperty("RawMaterialID")]
        public int RawMaterialID { get; set; }

        [JsonProperty("RMWhiteListID")]
        public int RMWhiteListID { get; set; }

        [JsonProperty("Status")]
        public byte Status { get; set; }

        [JsonProperty("IsConfirmed")]
        public bool IsConfirmed { get; set; }

        [JsonProperty("InsUserID")]
        public int InsUserID { get; set; }

        [JsonProperty("InsDate")]
        public string InsDate { get; set; }

        [JsonProperty("InsTime")]
        public string InsTime { get; set; }

        [JsonProperty("ConfirmerID")]
        public int? ConfirmerID { get; set; }

        [JsonProperty("ConfirmDate")]
        public string ConfirmDate { get; set; }

        [JsonProperty("ConfirmTime")]
        public string ConfirmTime { get; set; }

        [JsonProperty("ConfirmDescribe")]
        public string ConfirmDescribe { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)
    }
}