using System;
using System.Collections.Generic;
using System.Text;

using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class RawMaterialGroupTypesDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("RawMaterialGroupTypeID")]
        public short RawMaterialGroupTypeID { get; set; }

        [JsonProperty("RawMaterialGroupTypeName")]
        public string RawMaterialGroupTypeName { get; set; }

        [JsonProperty("RawMaterialGroupTypeLatinName")]
        public string RawMaterialGroupTypeLatinName { get; set; }

        [JsonProperty("IsLiquid")]
        public bool IsLiquid { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

    }
}
