using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class RawMaterialLotNumbersDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("RawMaterialLotNumberID")]
        public int RawMaterialLotNumberID { get; set; }

        [JsonProperty("RawMaterialID")]
        public int RawMaterialID { get; set; }

        [JsonProperty("RepeatNo")]
        public short RepeatNo { get; set; }

        [JsonProperty("LotNumber")]
        public string LotNumber { get; set; }

        [JsonProperty("Describe")]
        public string Describe { get; set; }

        [JsonProperty("InsUserID")]
        public int InsUserID { get; set; }

        [JsonProperty("InsDate")]
        public string InsDate { get; set; }

        [JsonProperty("InsTime")]
        public string InsTime { get; set; }

        [JsonProperty("EditUserID")]
        public int EditUserID { get; set; }

        [JsonProperty("EditDate")]
        public string EditDate { get; set; }

        [JsonProperty("EditTime")]
        public string EditTime { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

    }
}