using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class RawMaterialGroupsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("RawMaterialGroupID")]
        public short RawMaterialGroupID { get; set; }

        [JsonProperty("RawMaterialGroupName")]
        public string RawMaterialGroupName { get; set; }

        [JsonProperty("RawMaterialGroupLatinName")]
        public string RawMaterialGroupLatinName { get; set; }

        [JsonProperty("RawMaterialGroupTypeID")]
        public short RawMaterialGroupTypeID { get; set; }

        [JsonProperty("StorageConditions")]
        public string StorageConditions { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("RawMaterialGroupType")]
        public RawMaterialGroupTypesDTO RawMaterialGroupType { get; set; }


    }
}