using Newtonsoft.Json;
using System.Collections.Generic;

namespace PPC.Response.DTOs
{
    public class RawMaterialsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("RawMaterialID")]
        public int RawMaterialID { get; set; }

        [JsonProperty("RawMaterialOriginCode")]
        public string RawMaterialOriginCode { get; set; }

        [JsonProperty("RawMaterialOriginName")]
        public string RawMaterialOriginName { get; set; }

        [JsonProperty("RawMaterialCode")]
        public string RawMaterialCode { get; set; }

        [JsonProperty("RawMaterialName")]
        public string RawMaterialName { get; set; }

        [JsonProperty("RawMaterialLatinName")]
        public string RawMaterialLatinName { get; set; }

        [JsonProperty("UnitID")]
        public int UnitID { get; set; }

        [JsonProperty("RawMaterialGroupID")]
        public short RawMaterialGroupID { get; set; }

        [JsonProperty("SupplierID")]
        public short? SupplierID { get; set; }

        [JsonProperty("IsRecycled")]
        public bool IsRecycled { get; set; }

        [JsonProperty("StorageConditions")]
        public string StorageConditions { get; set; }

        [JsonProperty("SolidPercentage")]
        public decimal SolidPercentage { get; set; }

        [JsonProperty("IsSample")]
        public bool IsSample { get; set; }

        [JsonProperty("IsSemiProduct")]
        public bool IsSemiProduct { get; set; }

        [JsonProperty("HasBOMFormula")]
        public bool HasBOMFormula { get; set; } = false;

        [JsonProperty("RawMaterialSampleID")]
        public int? RawMaterialSampleID { get; set; }

        [JsonProperty("TestPlanAssignID")]
        public int TestPlanAssignID { get; set; }

        //[JsonProperty("ParentID")]
        //public int? ParentID { get; set; }

        [JsonProperty("IsConfirmed")]
        public bool? IsConfirmed { get; set; }

        [JsonProperty("InsUserID")]
        public int InsUserID { get; set; }

        [JsonProperty("InsDate")]
        public string InsDate { get; set; }

        [JsonProperty("InsTime")]
        public string InsTime { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }


        #endregion Base properties and methods(generated by  CodeGenerator)


        [JsonProperty("RawMaterialGroups")]
        public RawMaterialGroupsDTO RawMaterialGroups { get; set; }

        [JsonProperty("Units")]
        public UnitsDTO Units { get; set; }

        [JsonProperty("Supplier")]
        public SuppliersDTO Supplier { get; set; }

        [JsonProperty("RawMaterial_Sample")]
        public RawMaterialsDTO RawMaterial_Sample { get; set; }

        [JsonProperty("TestPlanAssign")]
        public TestPlanAssignDTO TestPlanAssign { get; set; }

        //[JsonProperty("Parent")]
        //public RawMaterialsDTO Parent { get; set; }

        [JsonProperty("LotNosList")]
        public List<RawMaterialLotNumbersDTO> LotNosList { get; set; }

        [JsonProperty("RMWhiteListAssign")]
        public List<RawMaterialWhiteListAssignDTO> RMWhiteListAssign { get; set; }


    }
}