using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class RMWhiteListsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("RMWhiteListID")]
        public int RMWhiteListID { get; set; }

        [JsonProperty("RMWhiteListCode")]
        public string RMWhiteListCode { get; set; }

        [JsonProperty("RMWhiteListName")]
        public string RMWhiteListName { get; set; }

        [JsonProperty("ProductSerieID")]
        public int ProductSerieID { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("ProductSerie")]
        public ProductSeriesDTO ProductSerie { get; set; }


    }
}