using System;
using System.Collections.Generic;
using System.Text;

using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class SaleAgentsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("SaleAgentID")]
        public short SaleAgentID { get; set; }

        [JsonProperty("SaleAgentCode")]
        public string SaleAgentCode { get; set; }

        [JsonProperty("SaleAgentName")]
        public string SaleAgentName { get; set; }

        [JsonProperty("SaleAgentLatinName")]
        public string SaleAgentLatinName { get; set; }

        [JsonProperty("SaleAgentLocalizedName")]
        public string SaleAgentLocalizedName { get; set; }

        [JsonProperty("ProvinceID")]
        public short ProvinceID { get; set; }

        [JsonProperty("IsForeign")]
        public bool IsForeign { get; set; }

        [JsonProperty("ContactPerson")]
        public string ContactPerson { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }

        [JsonProperty("Rating")]
        public decimal Rating { get; set; }

        [JsonProperty("CustomerGradeID")]
        public short CustomerGradeID { get; set; }

        [JsonProperty("StartDate")]
        public string StartDate { get; set; }

        [JsonProperty("Address")]
        public string Address { get; set; }

        [JsonProperty("Tel")]
        public string Tel { get; set; }

        [JsonProperty("ZipCode")]
        public string ZipCode { get; set; }

        #endregion  Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("Province")]
        public ProvincesDTO Province { get; set; }

        [JsonProperty("CustomerGrade")]
        public CustomerGradesDTO CustomerGrade { get; set; }


    }
}
