using Newtonsoft.Json;
using System;

namespace WebApi.Response.DTOs
{
    public class SettingsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("SettingID")]
        public int SettingID { get; set; }

        [JsonProperty("LastVersion")]
        public string LastVersion { get; set; }

        [JsonProperty("LastVersionWarninType")]
        public byte LastVersionWarninType { get; set; }

        [JsonProperty("UserID")]
        public Nullable<int> UserID { get; set; }

        [JsonProperty("StationID")]
        public Nullable<int> StationID { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("User")]
        public UsersDTO User { get; set; }

        [JsonProperty("Station")]
        public StationsDTO Station { get; set; }


    }
}