using Newtonsoft.Json;
namespace WebApi.Response.DTOs
{
    public class SettingUpdatesDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("UpdateID")]
        public int UpdateID { get; set; }

        [JsonProperty("Version")]
        public string Version { get; set; }

        [JsonProperty("ServerMap")]
        public string ServerMap { get; set; }

        [JsonProperty("FilesName")]
        public string FilesName { get; set; }

        [JsonProperty("Date")]
        public string Date { get; set; }

        [JsonProperty("Describe")]
        public string Describe { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

    }
}