using Newtonsoft.Json;
namespace WebApi.Response.DTOs
{
    public class StationTypesDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("StationTypeID")]
        public int StationTypeID { get; set; }

        [JsonProperty("StationTypeName")]
        public string StationTypeName { get; set; }

        [JsonProperty("StationTypeLatinName")]
        public string StationTypeLatinName { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }

        [JsonProperty("InsDate")]
        public string InsDate { get; set; }

        [JsonProperty("InsTime")]
        public string InsTime { get; set; }

        [JsonProperty("InsUserID")]
        public int InsUserID { get; set; }

        [JsonProperty("EditDate")]
        public string EditDate { get; set; }

        [JsonProperty("EditTime")]
        public string EditTime { get; set; }

        [JsonProperty("EditUserID")]
        public int EditUserID { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

    }
}