using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class SuppliersDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("SupplierID")]
        public short SupplierID { get; set; }

        [JsonProperty("SupplierCode")]
        public string SupplierCode { get; set; }

        [JsonProperty("SupplierName")]
        public string SupplierName { get; set; }

        [JsonProperty("SupplierLatinName")]
        public string SupplierLatinName { get; set; }

        [JsonProperty("SupplierOriginName")]
        public string SupplierOriginName { get; set; }

        [JsonProperty("ContactPerson")]
        public string ContactPerson { get; set; }

        [JsonProperty("ProvinceID")]
        public short? ProvinceID { get; set; }

        [JsonProperty("Tel")]
        public string Tel { get; set; }

        [JsonProperty("Address")]
        public string Address { get; set; }

        [JsonProperty("ZipCode")]
        public string ZipCode { get; set; }

        [JsonProperty("NationalIdentity")]
        public string NationalIdentity { get; set; }

        [JsonProperty("RegistrationNumber")]
        public string RegistrationNumber { get; set; }

        [JsonProperty("EconomicCode")]
        public string EconomicCode { get; set; }

        [JsonProperty("Rating")]
        public decimal Rating { get; set; }

        [JsonProperty("CustomerGradeID")]
        public short CustomerGradeID { get; set; }

        [JsonProperty("StartDate")]
        public string StartDate { get; set; }

        [JsonProperty("CEO")]
        public string CEO { get; set; }

        [JsonProperty("InsUserID")]
        public int InsUserID { get; set; }

        [JsonProperty("InsDate")]
        public string InsDate { get; set; }

        [JsonProperty("InsTime")]
        public string InsTime { get; set; }

        [JsonProperty("EditUserID")]
        public int EditUserID { get; set; }

        [JsonProperty("EditDate")]
        public string EditDate { get; set; }

        [JsonProperty("EditTime")]
        public string EditTime { get; set; }

        [JsonProperty("IsForeign")]
        public bool IsForeign { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)


        [JsonProperty("Province")]
        public ProvincesDTO Province { get; set; }

        [JsonProperty("CustomerGrade")]
        public CustomerGradesDTO CustomerGrade { get; set; }

        [JsonProperty("User_InsUser")]
        public UsersDTO User_InsUser { get; set; }

        [JsonProperty("User_EditUser")]
        public UsersDTO User_EditUser { get; set; }


    }
}
