using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class TestPlanDetailsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("TestPlanDetailID")]
        public int TestPlanDetailID { get; set; }

        [JsonProperty("TestPlanID")]
        public int TestPlanID { get; set; }

        [JsonProperty("TestPlanIndexID")]
        public int TestPlanIndexID { get; set; }

        [JsonProperty("MinVal")]
        public decimal? MinVal { get; set; }

        [JsonProperty("MaxVal")]
        public decimal? MaxVal { get; set; }

        [JsonProperty("TextPhrase")]
        public string TextPhrase { get; set; }

        [JsonProperty("UnitID")]
        public int UnitID { get; set; }

        [JsonProperty("DiagnosisMethod")]
        public string DiagnosisMethod { get; set; }

        [JsonProperty("TestTool")]
        public string TestTool { get; set; }

        [JsonProperty("TestStage")]
        public string TestStage { get; set; }

        [JsonProperty("InstructionID")]
        public short InstructionID { get; set; }

        [JsonProperty("Describe")]
        public string Describe { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("TestPlan")]
        public TestPlansDTO TestPlan { get; set; }


        [JsonProperty("TestPlanIndex")]
        public TestPlanIndexesDTO TestPlanIndex { get; set; }

        [JsonProperty("Unit")]
        public UnitsDTO Unit { get; set; }

        [JsonProperty("Instruction")]
        public InstructionsDTO Instruction { get; set; }


    }
}