using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class TestPlanGroupTypeAssignsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("TestPlanGroupTypeAssignID")]
        public short TestPlanGroupTypeAssignID { get; set; }

        [JsonProperty("TestPlanGroupID")]
        public byte TestPlanGroupID { get; set; }

        [JsonProperty("TestPlanEntranceType")]
        public byte TestPlanEntranceType { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

    }
}