using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class TestPlanBasicIndexDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("TestPlanBasicIndexID")]
        public short TestPlanBasicIndexID { get; set; }

        [JsonProperty("TestPlanIndexID")]
        public int TestPlanIndexID { get; set; }

        [JsonProperty("MinVal")]
        public decimal MinVal { get; set; }

        [JsonProperty("MaxVal")]
        public decimal MaxVal { get; set; }

        [JsonProperty("TextPhrase")]
        public string TextPhrase { get; set; }

        [JsonProperty("UnitID")]
        public int UnitID { get; set; }

        [JsonProperty("DiagnosisMethod")]
        public string DiagnosisMethod { get; set; }

        [JsonProperty("TestTool")]
        public string TestTool { get; set; }

        [JsonProperty("TestStage")]
        public string TestStage { get; set; }

        [JsonProperty("InstructionID")]
        public short InstructionID { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

    }
}