using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class TestPlanGroupsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("TestPlanGroupID")]
        public byte TestPlanGroupID { get; set; }

        [JsonProperty("TestPlanGroupCode")]
        public string TestPlanGroupCode { get; set; }

        [JsonProperty("TestPlanGroupName")]
        public string TestPlanGroupName { get; set; }

        [JsonProperty("TestPlanGroupSign")]
        public string TestPlanGroupSign { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)

    }
}