using Newtonsoft.Json;
using System.Collections.Generic;

namespace PPC.Response.DTOs
{
    public class TestPlansDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("TestPlanID")]
        public int TestPlanID { get; set; }

        [JsonProperty("MaterialTypeID")]
        public byte MaterialTypeID { get; set; }

        [JsonProperty("ProductTypeID")]
        public short? ProductTypeID { get; set; }

        [JsonProperty("RawMaterialGroupTypeID")]
        public int? RawMaterialGroupTypeID { get; set; }

        [JsonProperty("TestPlanMCode")]
        public string TestPlanMCode { get; set; }

        [JsonProperty("TestPlanCode")]
        public string TestPlanCode { get; set; }

        [JsonProperty("TestPlanCodeChar")]
        public string TestPlanCodeChar { get; set; }

        [JsonProperty("TestPlanCodeNum")]
        public string TestPlanCodeNum { get; set; }

        [JsonProperty("TestPlanCodeSeri")]
        public string TestPlanCodeSeri { get; set; }

        [JsonProperty("TestPlanCodeVersion")]
        public string TestPlanCodeVersion { get; set; }

        [JsonProperty("Version")]
        public short Version { get; set; }

        [JsonProperty("InsUserID")]
        public int InsUserID { get; set; }

        [JsonProperty("InsUserName")]
        public string InsUserName { get; set; }

        [JsonProperty("InsUserFullName")]
        public string InsUserFullName { get; set; }

        [JsonProperty("InsDate")]
        public string InsDate { get; set; }

        [JsonProperty("InsTime")]
        public string InsTime { get; set; }

        [JsonProperty("EditUserID")]
        public int EditUserID { get; set; }

        [JsonProperty("EditUserName")]
        public string EditUserName { get; set; }

        [JsonProperty("EditUserFullName")]
        public string EditUserFullName { get; set; }

        [JsonProperty("EditDate")]
        public string EditDate { get; set; }

        [JsonProperty("EditTime")]
        public string EditTime { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }

        [JsonProperty("LastNodeID")]
        public int? LastNodeID { get; set; }

        [JsonProperty("ParentID")]
        public int? ParentID { get; set; }

        [JsonProperty("Status")]
        public byte Status { get; set; }

        [JsonProperty("IsConfirmed")]
        public bool IsConfirmed { get; set; }


        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("ProductGroup")]
        public ProductGroupsDTO ProductGroup { get; set; }

        [JsonProperty("RawMaterialGroupType")]
        public RawMaterialGroupTypesDTO RawMaterialGroupType { get; set; }

        [JsonProperty("User_InsUser")]
        public UsersDTO User_InsUser { get; set; }

        [JsonProperty("User_EditUser")]
        public UsersDTO User_EditUser { get; set; }

        [JsonProperty("LastNode")]
        public TestPlansDTO LastNode { get; set; }

        [JsonProperty("Parent")]
        public TestPlansDTO Parent { get; set; }

        [JsonProperty("TestPlanDetails")]
        public List<TestPlanDetailsDTO> TestPlanDetails { get; set; }

        [JsonProperty("TestPlanAssign")]
        public List<TestPlanAssignDTO> TestPlanAssign { get; set; }



    }
}
