using Newtonsoft.Json;
using System.Collections.Generic;

namespace PPC.Response.DTOs
{
    public class TestPlanAssignDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("TestPlanAssignID")]
        public int TestPlanAssignID { get; set; }

        [JsonProperty("MaterialTypeID")]
        public byte MaterialTypeID { get; set; }

        [JsonProperty("ProductID")]
        public int? ProductID { get; set; }

        [JsonProperty("RawMaterialGroupTypeID")]
        public int? RawMaterialGroupTypeID { get; set; }

        [JsonProperty("TestPlanID")]
        public int TestPlanID { get; set; }

        [JsonProperty("TestPlanAssignedCode")]
        public string TestPlanAssignedCode { get; set; }

        [JsonProperty("AssignedCodeNum")]
        public short AssignedCodeNum { get; set; }

        [JsonProperty("Version")]
        public short Version { get; set; }

        [JsonProperty("InsUserID")]
        public int InsUserID { get; set; }

        [JsonProperty("InsUserName")]
        public string InsUserName { get; set; }

        [JsonProperty("InsUserFullName")]
        public string InsUserFullName { get; set; }

        [JsonProperty("InsDate")]
        public string InsDate { get; set; }

        [JsonProperty("InsTime")]
        public string InsTime { get; set; }

        [JsonProperty("EditUserID")]
        public int EditUserID { get; set; }

        [JsonProperty("EditUserName")]
        public string EditUserName { get; set; }

        [JsonProperty("EditUserFullName")]
        public string EditUserFullName { get; set; }

        [JsonProperty("EditDate")]
        public string EditDate { get; set; }

        [JsonProperty("EditTime")]
        public string EditTime { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }

        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("Product")]
        public ProductsDTO Product { get; set; }

        [JsonProperty("RawMaterialGroupType")]
        public RawMaterialGroupTypesDTO RawMaterialGroupType { get; set; }

        [JsonProperty("TestPlan")]
        public TestPlansDTO TestPlan { get; set; }

        [JsonProperty("User_InsUser")]
        public UsersDTO User_InsUser { get; set; }

        [JsonProperty("User_EditUser")]
        public UsersDTO User_EditUser { get; set; }

        [JsonProperty("TestPlanAssignDetails")]
        public List<TestPlanAssignDetailDTO> TestPlanAssignDetails { get; set; }




    }
}