using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class TestPlanIndexesDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("TestPlanIndexID")]
        public int TestPlanIndexID { get; set; }

        [JsonProperty("TestPlanIndexName")]
        public string TestPlanIndexName { get; set; }

        [JsonProperty("Describe")]
        public string Describe { get; set; }

        [JsonProperty("IsRawMaterialIndex")]
        public bool IsRawMaterialIndex { get; set; }

        [JsonProperty("IsProductIndex")]
        public bool IsProductIndex { get; set; }

        [JsonProperty("TestPlanIndexFieldTypeID")]
        public byte TestPlanIndexFieldTypeID { get; set; }

        [JsonProperty("IsActive")]
        public bool IsActive { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)
    }
}