using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class UserGroupsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("UserGroupID")]
        public int UserGroupID { get; set; }

        [JsonProperty("UserGroupName")]
        public string UserGroupName { get; set; }

        [JsonProperty("Describe")]
        public string Describe { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)
    }
}