using Newtonsoft.Json;
namespace WebApi.Response.DTOs
{
    public class UserGroupStationsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("UserGroupStationID")]
        public int UserGroupStationID { get; set; }

        [JsonProperty("UserGroupID")]
        public int UserGroupID { get; set; }

        [JsonProperty("StationID")]
        public int StationID { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)
    }
}