using Newtonsoft.Json;
namespace PPC.Response.DTOs
{
    public class UserGroupAssignsDTO
    {

        #region Base properties and methods(generated by  CodeGenerator)
        [JsonProperty("UserGroupAssignID")]
        public int UserGroupAssignID { get; set; }

        [JsonProperty("UserID")]
        public int UserID { get; set; }

        [JsonProperty("UserGroupID")]
        public int UserGroupID { get; set; }
        #endregion Base properties and methods(generated by  CodeGenerator)

        [JsonProperty("User")]
        public UsersDTO User { get; set; }


        [JsonProperty("UserGroup")]
        public UserGroupsDTO UserGroup { get; set; }

    }
}